/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.core.Variant;
import com.carto.geometry.Geometry;
import com.carto.geometry.Feature;

/** @hidden */
@com.carto.utils.DontObfuscate public class FeatureBuilderModuleJNI {
  public final static native long new_FeatureBuilder();
  public final static native void delete_FeatureBuilder(long jarg1);
  public final static native long FeatureBuilder_getGeometry(long jarg1, FeatureBuilder jarg1_);
  public final static native void FeatureBuilder_setGeometry(long jarg1, FeatureBuilder jarg1_, long jarg2, Geometry jarg2_);
  public final static native long FeatureBuilder_getPropertyValue(long jarg1, FeatureBuilder jarg1_, String jarg2);
  public final static native void FeatureBuilder_setPropertyValue(long jarg1, FeatureBuilder jarg1_, String jarg2, long jarg3, Variant jarg3_);
  public final static native long FeatureBuilder_buildFeature(long jarg1, FeatureBuilder jarg1_);
  public final static native long FeatureBuilder_swigGetRawPtr(long jarg1, FeatureBuilder jarg1_);
  public final static native String FeatureBuilder_swigGetClassName(long jarg1, FeatureBuilder jarg1_);
  public final static native Object FeatureBuilder_swigGetDirectorObject(long jarg1, FeatureBuilder jarg1_);
}
