/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.core.Variant;
import com.carto.geometry.Geometry;

/**
 * A feature consisting of geometry and properties.
 */
@com.carto.utils.DontObfuscate public class Feature {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public Feature(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(Feature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FeatureModuleJNI.delete_Feature(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.geometry.Feature swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.geometry.FeatureModuleJNI.Feature_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.geometry.Feature) director;
    }

    String objClassName = com.carto.geometry.FeatureModuleJNI.Feature_swigGetClassName(cPtr, null);
    com.carto.geometry.Feature objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.geometry." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.geometry.Feature) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof Feature) {
      return ((Feature)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * Constructs a Feature object from geometry and properties.<br>
 * @param geometry The geometry of the feature.<br>
 * @param properties The properties of the feature.
 */
  public Feature(Geometry geometry, Variant properties) {
    this(FeatureModuleJNI.new_Feature(Geometry.getCPtr(geometry), geometry, Variant.getCPtr(properties), properties), true);
  }

/**
 * Returns the geometry of the feature.<br>
 * @return The geometry of the feature.
 */
  public Geometry getGeometry() {
  long cPtr = FeatureModuleJNI.Feature_getGeometry(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.Geometry.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the properties of the feature.<br>
 * @return The properties of the feature.
 */
  public Variant getProperties() { return new Variant(FeatureModuleJNI.Feature_getProperties(swigCPtr, this), true); }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return FeatureModuleJNI.Feature_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return FeatureModuleJNI.Feature_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return FeatureModuleJNI.Feature_swigGetDirectorObject(swigCPtr, this);
  }

}
