/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

public class FeatureVector {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public FeatureVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(FeatureVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FeatureModuleJNI.delete_FeatureVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FeatureVector() {
    this(FeatureModuleJNI.new_FeatureVector__SWIG_0(), true);
  }

  public FeatureVector(long n) {
    this(FeatureModuleJNI.new_FeatureVector__SWIG_1(n), true);
  }

  public long size() {
    return FeatureModuleJNI.FeatureVector_size(swigCPtr, this);
  }

  public long capacity() {
    return FeatureModuleJNI.FeatureVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    FeatureModuleJNI.FeatureVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return FeatureModuleJNI.FeatureVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    FeatureModuleJNI.FeatureVector_clear(swigCPtr, this);
  }

  public void add(Feature x) {
    FeatureModuleJNI.FeatureVector_add(swigCPtr, this, Feature.getCPtr(x), x);
  }

  public Feature get(int i) {
  long cPtr = FeatureModuleJNI.FeatureVector_get(swigCPtr, this, i);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.Feature.swigCreatePolymorphicInstance(cPtr, true);
}

  public void set(int i, Feature val) {
    FeatureModuleJNI.FeatureVector_set(swigCPtr, this, i, Feature.getCPtr(val), val);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return FeatureModuleJNI.FeatureVector_swigGetRawPtr(swigCPtr, this);
  }

}
