/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.geometry.Geometry;
import com.carto.geometry.MultiGeometry;
import com.carto.geometry.LineGeometry;
import com.carto.geometry.LineGeometryVector;

/** @hidden */
@com.carto.utils.DontObfuscate public class MultiLineGeometryModuleJNI {
  public final static native long new_MultiLineGeometry(long jarg1, LineGeometryVector jarg1_);
  public final static native void delete_MultiLineGeometry(long jarg1);
  public final static native long MultiLineGeometry_getGeometry(long jarg1, MultiLineGeometry jarg1_, int jarg2);
  public final static native long MultiLineGeometry_swigGetRawPtr(long jarg1, MultiLineGeometry jarg1_);
  public final static native String MultiLineGeometry_swigGetClassName(long jarg1, MultiLineGeometry jarg1_);
  public final static native Object MultiLineGeometry_swigGetDirectorObject(long jarg1, MultiLineGeometry jarg1_);
  public final static native long MultiLineGeometry_SWIGSmartPtrUpcast(long jarg1);
}
