/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.geometry.Geometry;
import com.carto.geometry.MultiGeometry;
import com.carto.geometry.PolygonGeometry;
import com.carto.geometry.PolygonGeometryVector;

/** @hidden */
@com.carto.utils.DontObfuscate public class MultiPolygonGeometryModuleJNI {
  public final static native long new_MultiPolygonGeometry(long jarg1, PolygonGeometryVector jarg1_);
  public final static native void delete_MultiPolygonGeometry(long jarg1);
  public final static native long MultiPolygonGeometry_getGeometry(long jarg1, MultiPolygonGeometry jarg1_, int jarg2);
  public final static native long MultiPolygonGeometry_swigGetRawPtr(long jarg1, MultiPolygonGeometry jarg1_);
  public final static native String MultiPolygonGeometry_swigGetClassName(long jarg1, MultiPolygonGeometry jarg1_);
  public final static native Object MultiPolygonGeometry_swigGetDirectorObject(long jarg1, MultiPolygonGeometry jarg1_);
  public final static native long MultiPolygonGeometry_SWIGSmartPtrUpcast(long jarg1);
}
