/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

public class PointGeometryVector {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public PointGeometryVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(PointGeometryVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PointGeometryModuleJNI.delete_PointGeometryVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PointGeometryVector() {
    this(PointGeometryModuleJNI.new_PointGeometryVector__SWIG_0(), true);
  }

  public PointGeometryVector(long n) {
    this(PointGeometryModuleJNI.new_PointGeometryVector__SWIG_1(n), true);
  }

  public long size() {
    return PointGeometryModuleJNI.PointGeometryVector_size(swigCPtr, this);
  }

  public long capacity() {
    return PointGeometryModuleJNI.PointGeometryVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    PointGeometryModuleJNI.PointGeometryVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return PointGeometryModuleJNI.PointGeometryVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    PointGeometryModuleJNI.PointGeometryVector_clear(swigCPtr, this);
  }

  public void add(PointGeometry x) {
    PointGeometryModuleJNI.PointGeometryVector_add(swigCPtr, this, PointGeometry.getCPtr(x), x);
  }

  public PointGeometry get(int i) {
  long cPtr = PointGeometryModuleJNI.PointGeometryVector_get(swigCPtr, this, i);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.PointGeometry.swigCreatePolymorphicInstance(cPtr, true);
}

  public void set(int i, PointGeometry val) {
    PointGeometryModuleJNI.PointGeometryVector_set(swigCPtr, this, i, PointGeometry.getCPtr(val), val);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return PointGeometryModuleJNI.PointGeometryVector_swigGetRawPtr(swigCPtr, this);
  }

}
