/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.core.MapPos;
import com.carto.geometry.Geometry;

/** @hidden */
@com.carto.utils.DontObfuscate public class PointGeometryModuleJNI {
  public final static native long new_PointGeometry(long jarg1, MapPos jarg1_);
  public final static native void delete_PointGeometry(long jarg1);
  public final static native long PointGeometry_getCenterPos(long jarg1, PointGeometry jarg1_);
  public final static native long PointGeometry_getPos(long jarg1, PointGeometry jarg1_);
  public final static native long PointGeometry_swigGetRawPtr(long jarg1, PointGeometry jarg1_);
  public final static native String PointGeometry_swigGetClassName(long jarg1, PointGeometry jarg1_);
  public final static native Object PointGeometry_swigGetDirectorObject(long jarg1, PointGeometry jarg1_);
  public final static native long new_PointGeometryVector__SWIG_0();
  public final static native long new_PointGeometryVector__SWIG_1(long jarg1);
  public final static native long PointGeometryVector_size(long jarg1, PointGeometryVector jarg1_);
  public final static native long PointGeometryVector_capacity(long jarg1, PointGeometryVector jarg1_);
  public final static native void PointGeometryVector_reserve(long jarg1, PointGeometryVector jarg1_, long jarg2);
  public final static native boolean PointGeometryVector_isEmpty(long jarg1, PointGeometryVector jarg1_);
  public final static native void PointGeometryVector_clear(long jarg1, PointGeometryVector jarg1_);
  public final static native void PointGeometryVector_add(long jarg1, PointGeometryVector jarg1_, long jarg2, PointGeometry jarg2_);
  public final static native long PointGeometryVector_get(long jarg1, PointGeometryVector jarg1_, int jarg2);
  public final static native void PointGeometryVector_set(long jarg1, PointGeometryVector jarg1_, int jarg2, long jarg3, PointGeometry jarg3_);
  public final static native long PointGeometryVector_swigGetRawPtr(long jarg1, PointGeometryVector jarg1_);
  public final static native void delete_PointGeometryVector(long jarg1);
  public final static native long PointGeometry_SWIGSmartPtrUpcast(long jarg1);
}
