/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.core.MapPos;
import com.carto.core.MapPosVector;
import com.carto.core.MapPosVectorVector;
import com.carto.geometry.Geometry;

/** @hidden */
@com.carto.utils.DontObfuscate public class PolygonGeometryModuleJNI {
  public final static native long new_PolygonGeometry__SWIG_0(long jarg1, MapPosVector jarg1_);
  public final static native long new_PolygonGeometry__SWIG_1(long jarg1, MapPosVector jarg1_, long jarg2, MapPosVectorVector jarg2_);
  public final static native long new_PolygonGeometry__SWIG_2(long jarg1, MapPosVectorVector jarg1_);
  public final static native void delete_PolygonGeometry(long jarg1);
  public final static native long PolygonGeometry_getCenterPos(long jarg1, PolygonGeometry jarg1_);
  public final static native long PolygonGeometry_getPoses(long jarg1, PolygonGeometry jarg1_);
  public final static native long PolygonGeometry_getHoles(long jarg1, PolygonGeometry jarg1_);
  public final static native long PolygonGeometry_getRings(long jarg1, PolygonGeometry jarg1_);
  public final static native long PolygonGeometry_swigGetRawPtr(long jarg1, PolygonGeometry jarg1_);
  public final static native String PolygonGeometry_swigGetClassName(long jarg1, PolygonGeometry jarg1_);
  public final static native Object PolygonGeometry_swigGetDirectorObject(long jarg1, PolygonGeometry jarg1_);
  public final static native long new_PolygonGeometryVector__SWIG_0();
  public final static native long new_PolygonGeometryVector__SWIG_1(long jarg1);
  public final static native long PolygonGeometryVector_size(long jarg1, PolygonGeometryVector jarg1_);
  public final static native long PolygonGeometryVector_capacity(long jarg1, PolygonGeometryVector jarg1_);
  public final static native void PolygonGeometryVector_reserve(long jarg1, PolygonGeometryVector jarg1_, long jarg2);
  public final static native boolean PolygonGeometryVector_isEmpty(long jarg1, PolygonGeometryVector jarg1_);
  public final static native void PolygonGeometryVector_clear(long jarg1, PolygonGeometryVector jarg1_);
  public final static native void PolygonGeometryVector_add(long jarg1, PolygonGeometryVector jarg1_, long jarg2, PolygonGeometry jarg2_);
  public final static native long PolygonGeometryVector_get(long jarg1, PolygonGeometryVector jarg1_, int jarg2);
  public final static native void PolygonGeometryVector_set(long jarg1, PolygonGeometryVector jarg1_, int jarg2, long jarg3, PolygonGeometry jarg3_);
  public final static native long PolygonGeometryVector_swigGetRawPtr(long jarg1, PolygonGeometryVector jarg1_);
  public final static native void delete_PolygonGeometryVector(long jarg1);
  public final static native long PolygonGeometry_SWIGSmartPtrUpcast(long jarg1);
}
