/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geometry;

import com.carto.geometry.Geometry;

/** @hidden */
public class WKTGeometryReaderModuleJNI {
  public final static native long new_WKTGeometryReader();
  public final static native long WKTGeometryReader_readGeometry(long jarg1, WKTGeometryReader jarg1_, String jarg2);
  public final static native void delete_WKTGeometryReader(long jarg1);
}
