/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.packagemanager;

import com.carto.core.Variant;

/** @hidden */
public class PackageMetaInfoModuleJNI {
  public final static native long new_PackageMetaInfo(long jarg1, Variant jarg1_);
  public final static native long PackageMetaInfo_getVariant(long jarg1, PackageMetaInfo jarg1_);
  public final static native long PackageMetaInfo_swigGetRawPtr(long jarg1, PackageMetaInfo jarg1_);
  public final static native void delete_PackageMetaInfo(long jarg1);
}
