/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.packagemanager;

import com.carto.core.MapTile;
import com.carto.geometry.MultiPolygonGeometry;
import com.carto.projections.Projection;

/** @hidden */
public class PackageTileMaskModuleJNI {
  public final static native String PackageTileMask_getStringValue(long jarg1, PackageTileMask jarg1_);
  public final static native int PackageTileMask_getMaxZoomLevel(long jarg1, PackageTileMask jarg1_);
  public final static native long PackageTileMask_getBoundingPolygon(long jarg1, PackageTileMask jarg1_, long jarg2, Projection jarg2_);
  public final static native int PackageTileMask_getTileStatus(long jarg1, PackageTileMask jarg1_, long jarg2, MapTile jarg2_);
  public final static native long PackageTileMask_swigGetRawPtr(long jarg1, PackageTileMask jarg1_);
  public final static native void delete_PackageTileMask(long jarg1);
}
