/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.packagemanager;

/**
 * Tile status.
 */
public enum PackageTileStatus {
/**
 * Tile is not part of the package.
 */
  PACKAGE_TILE_STATUS_MISSING,
/**
 * Tile is part of the package, but package does not fully cover it.<br>
 * This value is no longer used, thus this is deprecated.
 */
  PACKAGE_TILE_STATUS_PARTIAL,
/**
 * Tile if part of the package and package fully covers it.
 */
  PACKAGE_TILE_STATUS_FULL;

  public final int swigValue() {
    return swigValue;
  }

  public static PackageTileStatus swigToEnum(int swigValue) {
    PackageTileStatus[] swigValues = PackageTileStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PackageTileStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PackageTileStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PackageTileStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PackageTileStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PackageTileStatus(PackageTileStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

