/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.datasources.components;

import com.carto.core.BinaryData;

/** @hidden */
public class TileDataModuleJNI {
  public final static native long new_TileData(long jarg1, BinaryData jarg1_);
  public final static native void delete_TileData(long jarg1);
  public final static native long TileData_getMaxAge(long jarg1, TileData jarg1_);
  public final static native void TileData_setMaxAge(long jarg1, TileData jarg1_, long jarg2);
  public final static native boolean TileData_isReplaceWithParent(long jarg1, TileData jarg1_);
  public final static native void TileData_setReplaceWithParent(long jarg1, TileData jarg1_, boolean jarg2);
  public final static native long TileData_getData(long jarg1, TileData jarg1_);
  public final static native long TileData_swigGetRawPtr(long jarg1, TileData jarg1_);
}
