/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.search;

import com.carto.search.SearchRequest;
import com.carto.geometry.FeatureCollection;
import com.carto.projections.Projection;

/**
 * A search service for finding features from a specified feature collection.
 */
@com.carto.utils.DontObfuscate public class FeatureCollectionSearchService {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public FeatureCollectionSearchService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(FeatureCollectionSearchService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FeatureCollectionSearchServiceModuleJNI.delete_FeatureCollectionSearchService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.search.FeatureCollectionSearchService swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.search.FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.search.FeatureCollectionSearchService) director;
    }

    String objClassName = com.carto.search.FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_swigGetClassName(cPtr, null);
    com.carto.search.FeatureCollectionSearchService objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.search." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.search.FeatureCollectionSearchService) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a FeatureCollectionSearchService for given feature collection.<br>
 * @param projection The projection to use for the feature collection.<br>
 * @param featureCollection The feature collection to search from.
 */
  public FeatureCollectionSearchService(Projection projection, FeatureCollection featureCollection) {
    this(FeatureCollectionSearchServiceModuleJNI.new_FeatureCollectionSearchService(Projection.getCPtr(projection), projection, FeatureCollection.getCPtr(featureCollection), featureCollection), true);
    FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Returns the projection of the feature collection of the search service.<br>
 * @return The projection of the feature collection of the search service.
 */
  public Projection getProjection() {
  long cPtr = FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_getProjection(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.projections.Projection.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the feature collection of the search service.<br>
 * @return The feature collection of the search service.
 */
  public FeatureCollection getFeatureCollection() {
  long cPtr = FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_getFeatureCollection(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.FeatureCollection.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the maximum number of results the search service returns.<br>
 * @return The maximum number of results the search service returns.
 */
  public int getMaxResults() {
    return FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_getMaxResults(swigCPtr, this);
  }

/**
 * Sets the maximum number of results the search service returns.<br>
 * The default number of results is 1000.<br>
 * @param maxResults The new maximum number of results the geocoding service returns.
 */
  public void setMaxResults(int maxResults) {
    FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_setMaxResults(swigCPtr, this, maxResults);
  }

/**
 * Searches for the features specified by search request from the feature collection bound to the service.<br>
 * @param request The search request containing search filters.<br>
 * @return The resulting feature collection containing features matching the request.
 */
  public FeatureCollection findFeatures(SearchRequest request) {
  long cPtr = (getClass() == FeatureCollectionSearchService.class) ? FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_findFeatures(swigCPtr, this, SearchRequest.getCPtr(request), request) : FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_findFeaturesSwigExplicitFeatureCollectionSearchService(swigCPtr, this, SearchRequest.getCPtr(request), request);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.FeatureCollection.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return FeatureCollectionSearchServiceModuleJNI.FeatureCollectionSearchService_swigGetDirectorObject(swigCPtr, this);
  }

}
