/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.search;

import com.carto.search.SearchRequest;
import com.carto.geometry.FeatureCollection;
import com.carto.projections.Projection;

/** @hidden */
@com.carto.utils.DontObfuscate public class FeatureCollectionSearchServiceModuleJNI {
  public final static native long new_FeatureCollectionSearchService(long jarg1, Projection jarg1_, long jarg2, FeatureCollection jarg2_);
  public final static native void delete_FeatureCollectionSearchService(long jarg1);
  public final static native long FeatureCollectionSearchService_getProjection(long jarg1, FeatureCollectionSearchService jarg1_);
  public final static native long FeatureCollectionSearchService_getFeatureCollection(long jarg1, FeatureCollectionSearchService jarg1_);
  public final static native int FeatureCollectionSearchService_getMaxResults(long jarg1, FeatureCollectionSearchService jarg1_);
  public final static native void FeatureCollectionSearchService_setMaxResults(long jarg1, FeatureCollectionSearchService jarg1_, int jarg2);
  public final static native long FeatureCollectionSearchService_findFeatures(long jarg1, FeatureCollectionSearchService jarg1_, long jarg2, SearchRequest jarg2_);
  public final static native long FeatureCollectionSearchService_findFeaturesSwigExplicitFeatureCollectionSearchService(long jarg1, FeatureCollectionSearchService jarg1_, long jarg2, SearchRequest jarg2_);
  public final static native long FeatureCollectionSearchService_swigGetRawPtr(long jarg1, FeatureCollectionSearchService jarg1_);
  public final static native String FeatureCollectionSearchService_swigGetClassName(long jarg1, FeatureCollectionSearchService jarg1_);
  public final static native Object FeatureCollectionSearchService_swigGetDirectorObject(long jarg1, FeatureCollectionSearchService jarg1_);
  public final static native void FeatureCollectionSearchService_director_connect(FeatureCollectionSearchService obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void FeatureCollectionSearchService_change_ownership(FeatureCollectionSearchService obj, long cptr, boolean take_or_release);

  public static long SwigDirector_FeatureCollectionSearchService_findFeatures(FeatureCollectionSearchService self, long request) {
    return FeatureCollection.getCPtr(self.findFeatures(new SearchRequest(request, true)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
