/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.search;

import com.carto.search.SearchRequest;
import com.carto.datasources.TileDataSource;
import com.carto.geometry.VectorTileFeatureCollection;
import com.carto.vectortiles.VectorTileDecoder;
import com.carto.projections.Projection;

/**
 * A search service for finding features from the specified vector tile data source.<br>
 * Depending on the datasource, searching may perform network requests and must be executed in non-UI background thread.
 */
@com.carto.utils.DontObfuscate public class VectorTileSearchService {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public VectorTileSearchService(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(VectorTileSearchService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VectorTileSearchServiceModuleJNI.delete_VectorTileSearchService(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    VectorTileSearchServiceModuleJNI.VectorTileSearchService_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    VectorTileSearchServiceModuleJNI.VectorTileSearchService_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.search.VectorTileSearchService swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.search.VectorTileSearchServiceModuleJNI.VectorTileSearchService_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.search.VectorTileSearchService) director;
    }

    String objClassName = com.carto.search.VectorTileSearchServiceModuleJNI.VectorTileSearchService_swigGetClassName(cPtr, null);
    com.carto.search.VectorTileSearchService objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.search." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.search.VectorTileSearchService) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a VectorTileSearchService for the given vector data source and vector tile decoder.<br>
 * @param dataSource The vector data source to search from.<br>
 * @param tileDecoder The vector tile decoder to use for decoding the tiles.
 */
  public VectorTileSearchService(TileDataSource dataSource, VectorTileDecoder tileDecoder) {
    this(VectorTileSearchServiceModuleJNI.new_VectorTileSearchService(TileDataSource.getCPtr(dataSource), dataSource, VectorTileDecoder.getCPtr(tileDecoder), tileDecoder), true);
    VectorTileSearchServiceModuleJNI.VectorTileSearchService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Returns the tile data source of the search service.<br>
 * @return The tile data source of the search service.
 */
  public TileDataSource getDataSource() {
  long cPtr = VectorTileSearchServiceModuleJNI.VectorTileSearchService_getDataSource(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.datasources.TileDataSource.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the tile decoder used by the search service.<br>
 * @return The tile decoder used by the search service.
 */
  public VectorTileDecoder getTileDecoder() {
  long cPtr = VectorTileSearchServiceModuleJNI.VectorTileSearchService_getTileDecoder(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.vectortiles.VectorTileDecoder.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the minimum zoom level of vector tiles used.<br>
 * By default the minimum zoom level is specified by data source and is usually 0.<br>
 * @return The minimum zoom level of vector tiles used.
 */
  public int getMinZoom() {
    return VectorTileSearchServiceModuleJNI.VectorTileSearchService_getMinZoom(swigCPtr, this);
  }

/**
 * Sets the minimum zoom level of vector tiles used.<br>
 * @param minZoom The new minimum zoom level.
 */
  public void setMinZoom(int minZoom) {
    VectorTileSearchServiceModuleJNI.VectorTileSearchService_setMinZoom(swigCPtr, this, minZoom);
  }

/**
 * Returns the maximum zoom level of vector tiles used.<br>
 * By default the maximum zoom level is specified by data source.<br>
 * @return The maximum zoom level of vector tiles used.
 */
  public int getMaxZoom() {
    return VectorTileSearchServiceModuleJNI.VectorTileSearchService_getMaxZoom(swigCPtr, this);
  }

/**
 * Sets the maximum zoom level of vector tiles used.<br>
 * @param maxZoom The new maximum zoom level.
 */
  public void setMaxZoom(int maxZoom) {
    VectorTileSearchServiceModuleJNI.VectorTileSearchService_setMaxZoom(swigCPtr, this, maxZoom);
  }

/**
 * Returns the maximum number of results the search service returns.<br>
 * @return The maximum number of results the search service returns.
 */
  public int getMaxResults() {
    return VectorTileSearchServiceModuleJNI.VectorTileSearchService_getMaxResults(swigCPtr, this);
  }

/**
 * Sets the maximum number of results the search service returns.<br>
 * The default number of results is 1000.<br>
 * @param maxResults The new maximum number of results the geocoding service returns.
 */
  public void setMaxResults(int maxResults) {
    VectorTileSearchServiceModuleJNI.VectorTileSearchService_setMaxResults(swigCPtr, this, maxResults);
  }

/**
 * Searches for the features specified by search request from the vector tiles bound to the service.<br>
 * The zoom level range used for searching is specified using minZoom/maxZoom attributes of the search service.<br>
 * Depending on the data source, this method may perform slow IO operations and may need to be run in background thread.<br>
 * @param request The search request containing search filters.<br>
 * @return The resulting feature collection containing features matching the request.
 */
  public VectorTileFeatureCollection findFeatures(SearchRequest request) {
  long cPtr = (getClass() == VectorTileSearchService.class) ? VectorTileSearchServiceModuleJNI.VectorTileSearchService_findFeatures(swigCPtr, this, SearchRequest.getCPtr(request), request) : VectorTileSearchServiceModuleJNI.VectorTileSearchService_findFeaturesSwigExplicitVectorTileSearchService(swigCPtr, this, SearchRequest.getCPtr(request), request);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.VectorTileFeatureCollection.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return VectorTileSearchServiceModuleJNI.VectorTileSearchService_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return VectorTileSearchServiceModuleJNI.VectorTileSearchService_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return VectorTileSearchServiceModuleJNI.VectorTileSearchService_swigGetDirectorObject(swigCPtr, this);
  }

}
