/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.services;

import com.carto.core.Variant;
import com.carto.core.IntVector;
import com.carto.core.StringVariantMap;
import com.carto.core.StringMap;
import com.carto.core.StringVector;
import com.carto.layers.Layer;
import com.carto.layers.LayerVector;
import com.carto.utils.AssetPackage;

/** @hidden */
public class CartoMapsServiceModuleJNI {
  public final static native long new_CartoMapsService();
  public final static native void delete_CartoMapsService(long jarg1);
  public final static native String CartoMapsService_getUsername(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setUsername(long jarg1, CartoMapsService jarg1_, String jarg2);
  public final static native String CartoMapsService_getAPIKey(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setAPIKey(long jarg1, CartoMapsService jarg1_, String jarg2);
  public final static native String CartoMapsService_getAPITemplate(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setAPITemplate(long jarg1, CartoMapsService jarg1_, String jarg2);
  public final static native boolean CartoMapsService_isInteractive(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setInteractive(long jarg1, CartoMapsService jarg1_, boolean jarg2);
  public final static native long CartoMapsService_getLayerIndices(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setLayerIndices(long jarg1, CartoMapsService jarg1_, long jarg2, IntVector jarg2_);
  public final static native long CartoMapsService_getAuthTokens(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setAuthTokens(long jarg1, CartoMapsService jarg1_, long jarg2, StringVector jarg2_);
  public final static native boolean CartoMapsService_isDefaultVectorLayerMode(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setDefaultVectorLayerMode(long jarg1, CartoMapsService jarg1_, boolean jarg2);
  public final static native float CartoMapsService_getVectorTileBufferSize(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setVectorTileBufferSize(long jarg1, CartoMapsService jarg1_, float jarg2);
  public final static native boolean CartoMapsService_isStrictMode(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setStrictMode(long jarg1, CartoMapsService jarg1_, boolean jarg2);
  public final static native long CartoMapsService_getVectorTileAssetPackage(long jarg1, CartoMapsService jarg1_);
  public final static native void CartoMapsService_setVectorTileAssetPackage(long jarg1, CartoMapsService jarg1_, long jarg2, AssetPackage jarg2_);
  public final static native long CartoMapsService_buildMap(long jarg1, CartoMapsService jarg1_, long jarg2, Variant jarg2_) throws java.io.IOException;
  public final static native long CartoMapsService_buildNamedMap(long jarg1, CartoMapsService jarg1_, String jarg2, long jarg3, StringVariantMap jarg3_) throws java.io.IOException;
  public final static native long CartoMapsService_swigGetRawPtr(long jarg1, CartoMapsService jarg1_);
}
