/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.components;

import com.carto.layers.Layer;
import com.carto.layers.LayerVector;

/** @hidden */
public class LayersModuleJNI {
  public final static native void delete_Layers(long jarg1);
  public final static native int Layers_count(long jarg1, Layers jarg1_);
  public final static native void Layers_clear(long jarg1, Layers jarg1_);
  public final static native long Layers_get(long jarg1, Layers jarg1_, int jarg2);
  public final static native long Layers_getAll(long jarg1, Layers jarg1_);
  public final static native void Layers_set(long jarg1, Layers jarg1_, int jarg2, long jarg3, Layer jarg3_);
  public final static native void Layers_setAll(long jarg1, Layers jarg1_, long jarg2, LayerVector jarg2_);
  public final static native void Layers_insert(long jarg1, Layers jarg1_, int jarg2, long jarg3, Layer jarg3_);
  public final static native void Layers_add(long jarg1, Layers jarg1_, long jarg2, Layer jarg2_);
  public final static native void Layers_addAll(long jarg1, Layers jarg1_, long jarg2, LayerVector jarg2_);
  public final static native boolean Layers_remove(long jarg1, Layers jarg1_, long jarg2, Layer jarg2_);
  public final static native boolean Layers_removeAll(long jarg1, Layers jarg1_, long jarg2, LayerVector jarg2_);
  public final static native long Layers_swigGetRawPtr(long jarg1, Layers jarg1_);
}
