/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.ui;

/**
 * Possible click types.
 */
public enum ClickType {
/**
 * A click caused by pressing down and then releasing the screen.
 */
  CLICK_TYPE_SINGLE,
/**
 * A click caused by pressing down but not releasing the screen.
 */
  CLICK_TYPE_LONG,
/**
 * A click caused by two fast consecutive taps on the screen.
 */
  CLICK_TYPE_DOUBLE,
/**
 * A click caused by two simultaneous taps on the screen.
 */
  CLICK_TYPE_DUAL;

  public final int swigValue() {
    return swigValue;
  }

  public static ClickType swigToEnum(int swigValue) {
    ClickType[] swigValues = ClickType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ClickType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ClickType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ClickType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ClickType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ClickType(ClickType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

