/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.ui;


/**
 * A container class that provides information about a map interaction performed from UI.
 */
public class MapInteractionInfo {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public MapInteractionInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(MapInteractionInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MapInteractionInfoModuleJNI.delete_MapInteractionInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof MapInteractionInfo) {
      return ((MapInteractionInfo)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * Returns true if the interaction included a map pan action.<br>
 * @return True if the interaction included a map pan action.
 */
  public boolean isPanAction() {
    return MapInteractionInfoModuleJNI.MapInteractionInfo_isPanAction(swigCPtr, this);
  }

/**
 * Returns true if the interaction included a zoom action.<br>
 * @return True if the interaction included a zoom action.
 */
  public boolean isZoomAction() {
    return MapInteractionInfoModuleJNI.MapInteractionInfo_isZoomAction(swigCPtr, this);
  }

/**
 * Returns true if the interaction included a rotate action.<br>
 * @return True if the interaction included a rotate action.
 */
  public boolean isRotateAction() {
    return MapInteractionInfoModuleJNI.MapInteractionInfo_isRotateAction(swigCPtr, this);
  }

/**
 * Returns true if the interaction included a tilt action.<br>
 * @return True if the interaction included a tilt action.
 */
  public boolean isTiltAction() {
    return MapInteractionInfoModuleJNI.MapInteractionInfo_isTiltAction(swigCPtr, this);
  }

/**
 * Returns true if the interaction has started an animation.<br>
 * @return True if the interaction has started an animation.
 */
  public boolean isAnimationStarted() {
    return MapInteractionInfoModuleJNI.MapInteractionInfo_isAnimationStarted(swigCPtr, this);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return MapInteractionInfoModuleJNI.MapInteractionInfo_swigGetRawPtr(swigCPtr, this);
  }

}
