/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.ui;

import com.carto.core.MapPos;
import com.carto.core.ScreenPos;
import com.carto.vectorelements.Popup;
import com.carto.ui.ClickInfo;

/** @hidden */
public class PopupClickInfoModuleJNI {
  public final static native void delete_PopupClickInfo(long jarg1);
  public final static native int PopupClickInfo_getClickType(long jarg1, PopupClickInfo jarg1_);
  public final static native long PopupClickInfo_getClickInfo(long jarg1, PopupClickInfo jarg1_);
  public final static native long PopupClickInfo_getClickPos(long jarg1, PopupClickInfo jarg1_);
  public final static native long PopupClickInfo_getElementClickPos(long jarg1, PopupClickInfo jarg1_);
  public final static native long PopupClickInfo_getPopup(long jarg1, PopupClickInfo jarg1_);
  public final static native long PopupClickInfo_swigGetRawPtr(long jarg1, PopupClickInfo jarg1_);
}
