/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.ui;

import com.carto.core.MapPos;
import com.carto.core.ScreenPos;
import com.carto.vectorelements.Popup;
import com.carto.ui.ClickInfo;

/**
 * A container class that provides information about a click performed on<br>
 * a popup.
 */
public class PopupClickInfo {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public PopupClickInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(PopupClickInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PopupClickInfoModuleJNI.delete_PopupClickInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof PopupClickInfo) {
      return ((PopupClickInfo)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * Returns the click type.<br>
 * @return The type of the click performed.
 */
  public ClickType getClickType() {
    return ClickType.swigToEnum(PopupClickInfoModuleJNI.PopupClickInfo_getClickType(swigCPtr, this));
  }

/**
 * Returns the click info.<br>
 * @return The attributes of the click.
 */
  public ClickInfo getClickInfo() { return new ClickInfo(PopupClickInfoModuleJNI.PopupClickInfo_getClickInfo(swigCPtr, this), true); }

/**
 * Returns the click position.<br>
 * @return The click position in the coordinate system of the data source.
 */
  public MapPos getClickPos() { return new MapPos(PopupClickInfoModuleJNI.PopupClickInfo_getClickPos(swigCPtr, this), true); }

/**
 * Returns the 2D click position on the clicked popup.<br>
 * @return The 2D element click position in pixels.
 */
  public ScreenPos getElementClickPos() { return new ScreenPos(PopupClickInfoModuleJNI.PopupClickInfo_getElementClickPos(swigCPtr, this), true); }

/**
 * Returns the clicked popup.<br>
 * @return The popup on which the click was performed.
 */
  public Popup getPopup() {
  long cPtr = PopupClickInfoModuleJNI.PopupClickInfo_getPopup(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.vectorelements.Popup.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return PopupClickInfoModuleJNI.PopupClickInfo_swigGetRawPtr(swigCPtr, this);
  }

}
