/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.ui;

/**
 * Possible drag modes.
 */
public enum VectorElementDragMode {
/**
 * A single vertex is being moved.
 */
  VECTOR_ELEMENT_DRAG_MODE_VERTEX,
/**
 * The whole vector element is being moved.
 */
  VECTOR_ELEMENT_DRAG_MODE_ELEMENT;

  public final int swigValue() {
    return swigValue;
  }

  public static VectorElementDragMode swigToEnum(int swigValue) {
    VectorElementDragMode[] swigValues = VectorElementDragMode.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VectorElementDragMode swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VectorElementDragMode.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VectorElementDragMode() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VectorElementDragMode(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VectorElementDragMode(VectorElementDragMode swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

