/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.core;


/**
 * A wrapper class for binary data (Blob).
 */
public class BinaryData {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public BinaryData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(BinaryData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BinaryDataModuleJNI.delete_BinaryData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof BinaryData) {
      return ((BinaryData)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * Constructs an empty BinaryData object.
 */
  public BinaryData() {
    this(BinaryDataModuleJNI.new_BinaryData__SWIG_0(), true);
  }

/**
 * Constructs a BinaryData object from a raw byte array.<br>
 * @param dataPtr The raw pointer to the data.<br>
 * @param size The size of the data in bytes.
 */
  public BinaryData(byte[] dataPtr) {
    this(BinaryDataModuleJNI.new_BinaryData__SWIG_1(dataPtr), true);
  }

/**
 * Returns the size of the data<br>
 * @return The size of the data.
 */
  public long size() {
    return BinaryDataModuleJNI.BinaryData_size(swigCPtr, this);
  }

/**
 * Returns the data array.<br>
 * @return The data array.
 */
  public byte[] getData() {
  return BinaryDataModuleJNI.BinaryData_getData(swigCPtr, this);
}

/**
 * Creates a string representation of this map bounds object, useful for logging.<br>
 * @return The string representation of this map bounds object.
 */
  public String toString() {
    return BinaryDataModuleJNI.BinaryData_toString(swigCPtr, this);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return BinaryDataModuleJNI.BinaryData_swigGetRawPtr(swigCPtr, this);
  }

}
