/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.core;

public class StringMap {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public StringMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(StringMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        StringMapModuleJNI.delete_StringMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringMap() {
    this(StringMapModuleJNI.new_StringMap__SWIG_0(), true);
  }

  public StringMap(StringMap arg0) {
    this(StringMapModuleJNI.new_StringMap__SWIG_1(StringMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return StringMapModuleJNI.StringMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return StringMapModuleJNI.StringMap_empty(swigCPtr, this);
  }

  public void clear() {
    StringMapModuleJNI.StringMap_clear(swigCPtr, this);
  }

  public String get(String key) {
    return StringMapModuleJNI.StringMap_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    StringMapModuleJNI.StringMap_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    StringMapModuleJNI.StringMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return StringMapModuleJNI.StringMap_has_key(swigCPtr, this, key);
  }

  public String get_key(long idx) {
    return StringMapModuleJNI.StringMap_get_key(swigCPtr, this, idx);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return StringMapModuleJNI.StringMap_swigGetRawPtr(swigCPtr, this);
  }

}
