/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.core;

public class VariantVector {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public VariantVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(VariantVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VariantModuleJNI.delete_VariantVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VariantVector() {
    this(VariantModuleJNI.new_VariantVector__SWIG_0(), true);
  }

  public VariantVector(long n) {
    this(VariantModuleJNI.new_VariantVector__SWIG_1(n), true);
  }

  public long size() {
    return VariantModuleJNI.VariantVector_size(swigCPtr, this);
  }

  public long capacity() {
    return VariantModuleJNI.VariantVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    VariantModuleJNI.VariantVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return VariantModuleJNI.VariantVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    VariantModuleJNI.VariantVector_clear(swigCPtr, this);
  }

  public void add(Variant x) {
    VariantModuleJNI.VariantVector_add(swigCPtr, this, Variant.getCPtr(x), x);
  }

  public Variant get(int i) { return new Variant(VariantModuleJNI.VariantVector_get(swigCPtr, this, i), true); }

  public void set(int i, Variant val) {
    VariantModuleJNI.VariantVector_set(swigCPtr, this, i, Variant.getCPtr(val), val);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return VariantModuleJNI.VariantVector_swigGetRawPtr(swigCPtr, this);
  }

}
