/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.core;

/**
 * A helper class for building variant objects.
 */
public class VariantObjectBuilder {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public VariantObjectBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(VariantObjectBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VariantObjectBuilderModuleJNI.delete_VariantObjectBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof VariantObjectBuilder) {
      return ((VariantObjectBuilder)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * A default constructor.
 */
  public VariantObjectBuilder() {
    this(VariantObjectBuilderModuleJNI.new_VariantObjectBuilder(), true);
  }

/**
 * Clears the object.
 */
  public void clear() {
    VariantObjectBuilderModuleJNI.VariantObjectBuilder_clear(swigCPtr, this);
  }

/**
 * Sets a specified string value.<br>
 * @param key The key to set.<br>
 * @param str The string value.
 */
  public void setString(String key, String str) {
    VariantObjectBuilderModuleJNI.VariantObjectBuilder_setString(swigCPtr, this, key, str);
  }

/**
 * Sets a specified boolean value.<br>
 * @param key The key to set.<br>
 * @param val The boolean value.
 */
  public void setBool(String key, boolean val) {
    VariantObjectBuilderModuleJNI.VariantObjectBuilder_setBool(swigCPtr, this, key, val);
  }

/**
 * Sets a specified long integer value.<br>
 * @param key The key to set.<br>
 * @param val The integer value.
 */
  public void setLong(String key, long val) {
    VariantObjectBuilderModuleJNI.VariantObjectBuilder_setLong(swigCPtr, this, key, val);
  }

/**
 * Sets a specified double precision floating point value.<br>
 * @param key The key to set.<br>
 * @param val The floating point value.
 */
  public void setDouble(String key, double val) {
    VariantObjectBuilderModuleJNI.VariantObjectBuilder_setDouble(swigCPtr, this, key, val);
  }

/**
 * Sets a specified variant value.<br>
 * @param key The key to set.<br>
 * @param var The variant to add.
 */
  public void setVariant(String key, Variant var) {
    VariantObjectBuilderModuleJNI.VariantObjectBuilder_setVariant(swigCPtr, this, key, Variant.getCPtr(var), var);
  }

/**
 * Builds a new object variant from the added elements.<br>
 * @return The corresponding variant object.
 */
  public Variant buildVariant() { return new Variant(VariantObjectBuilderModuleJNI.VariantObjectBuilder_buildVariant(swigCPtr, this), true); }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return VariantObjectBuilderModuleJNI.VariantObjectBuilder_swigGetRawPtr(swigCPtr, this);
  }

}
