/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.core;

import com.carto.core.Variant;

/** @hidden */
public class VariantArrayBuilderModuleJNI {
  public final static native long new_VariantArrayBuilder();
  public final static native void VariantArrayBuilder_clear(long jarg1, VariantArrayBuilder jarg1_);
  public final static native void VariantArrayBuilder_addString(long jarg1, VariantArrayBuilder jarg1_, String jarg2);
  public final static native void VariantArrayBuilder_addBool(long jarg1, VariantArrayBuilder jarg1_, boolean jarg2);
  public final static native void VariantArrayBuilder_addLong(long jarg1, VariantArrayBuilder jarg1_, long jarg2);
  public final static native void VariantArrayBuilder_addDouble(long jarg1, VariantArrayBuilder jarg1_, double jarg2);
  public final static native void VariantArrayBuilder_addVariant(long jarg1, VariantArrayBuilder jarg1_, long jarg2, Variant jarg2_);
  public final static native long VariantArrayBuilder_buildVariant(long jarg1, VariantArrayBuilder jarg1_);
  public final static native long VariantArrayBuilder_swigGetRawPtr(long jarg1, VariantArrayBuilder jarg1_);
  public final static native void delete_VariantArrayBuilder(long jarg1);
}
