/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.projections;

import com.carto.core.MapBounds;
import com.carto.core.MapPos;
import com.carto.projections.Projection;

/** @hidden */
@com.carto.utils.DontObfuscate public class EPSG3857ModuleJNI {
  public final static native long new_EPSG3857();
  public final static native void delete_EPSG3857(long jarg1);
  public final static native long EPSG3857_fromWgs84(long jarg1, EPSG3857 jarg1_, long jarg2, MapPos jarg2_);
  public final static native long EPSG3857_toWgs84(long jarg1, EPSG3857 jarg1_, long jarg2, MapPos jarg2_);
  public final static native String EPSG3857_getName(long jarg1, EPSG3857 jarg1_);
  public final static native long EPSG3857_swigGetRawPtr(long jarg1, EPSG3857 jarg1_);
  public final static native String EPSG3857_swigGetClassName(long jarg1, EPSG3857 jarg1_);
  public final static native Object EPSG3857_swigGetDirectorObject(long jarg1, EPSG3857 jarg1_);
  public final static native long EPSG3857_SWIGSmartPtrUpcast(long jarg1);
}
