/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.utils;

import com.carto.core.BinaryData;
import com.carto.core.StringVector;

/**
 * An abstract asset package class. Contains methods to list and load assets.
 */
@com.carto.utils.DontObfuscate public class AssetPackage {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public AssetPackage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(AssetPackage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AssetPackageModuleJNI.delete_AssetPackage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AssetPackageModuleJNI.AssetPackage_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AssetPackageModuleJNI.AssetPackage_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.utils.AssetPackage swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.utils.AssetPackageModuleJNI.AssetPackage_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.utils.AssetPackage) director;
    }

    String objClassName = com.carto.utils.AssetPackageModuleJNI.AssetPackage_swigGetClassName(cPtr, null);
    com.carto.utils.AssetPackage objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.utils." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.utils.AssetPackage) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof AssetPackage) {
      return ((AssetPackage)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * Returns list of assets in the asset package.<br>
 * All listed assets can read using loadAsset API.<br>
 * @return List of asset names.
 */
  public StringVector getAssetNames() { return new StringVector(AssetPackageModuleJNI.AssetPackage_getAssetNames(swigCPtr, this), true); }

/**
 * Loads the specified asset from the asset package.<br>
 * @param name The asset name to read.<br>
 * @return Asset data, if the asset exists and was successfully read. Null pointer otherwise.
 */
  public BinaryData loadAsset(String name) {
    long cPtr = AssetPackageModuleJNI.AssetPackage_loadAsset(swigCPtr, this, name);
    return (cPtr == 0) ? null : new BinaryData(cPtr, true);
  }

  protected AssetPackage() {
    this(AssetPackageModuleJNI.new_AssetPackage(), true);
    AssetPackageModuleJNI.AssetPackage_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return AssetPackageModuleJNI.AssetPackage_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return AssetPackageModuleJNI.AssetPackage_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return AssetPackageModuleJNI.AssetPackage_swigGetDirectorObject(swigCPtr, this);
  }

}
