/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.graphics.Color;
import com.carto.graphics.Bitmap;
import com.carto.styles.PopupStyleBuilder;
import com.carto.styles.BalloonPopupStyle;

/** @hidden */
@com.carto.utils.DontObfuscate public class BalloonPopupStyleBuilderModuleJNI {
  public final static native long new_BalloonPopupStyleBuilder();
  public final static native void delete_BalloonPopupStyleBuilder(long jarg1);
  public final static native int BalloonPopupStyleBuilder_getCornerRadius(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setCornerRadius(long jarg1, BalloonPopupStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupStyleBuilder_getLeftColor(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setLeftColor(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native long BalloonPopupStyleBuilder_getLeftImage(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setLeftImage(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Bitmap jarg2_);
  public final static native long BalloonPopupStyleBuilder_getLeftMargins(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setLeftMargins(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, BalloonPopupMargins jarg2_);
  public final static native long BalloonPopupStyleBuilder_getRightColor(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setRightColor(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native long BalloonPopupStyleBuilder_getRightImage(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setRightImage(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Bitmap jarg2_);
  public final static native long BalloonPopupStyleBuilder_getRightMargins(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setRightMargins(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, BalloonPopupMargins jarg2_);
  public final static native long BalloonPopupStyleBuilder_getTitleColor(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTitleColor(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native String BalloonPopupStyleBuilder_getTitleFontName(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTitleFontName(long jarg1, BalloonPopupStyleBuilder jarg1_, String jarg2);
  public final static native String BalloonPopupStyleBuilder_getTitleField(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTitleField(long jarg1, BalloonPopupStyleBuilder jarg1_, String jarg2);
  public final static native int BalloonPopupStyleBuilder_getTitleFontSize(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTitleFontSize(long jarg1, BalloonPopupStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupStyleBuilder_getTitleMargins(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTitleMargins(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, BalloonPopupMargins jarg2_);
  public final static native boolean BalloonPopupStyleBuilder_isTitleWrap(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTitleWrap(long jarg1, BalloonPopupStyleBuilder jarg1_, boolean jarg2);
  public final static native long BalloonPopupStyleBuilder_getDescriptionColor(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setDescriptionColor(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native String BalloonPopupStyleBuilder_getDescriptionFontName(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setDescriptionFontName(long jarg1, BalloonPopupStyleBuilder jarg1_, String jarg2);
  public final static native String BalloonPopupStyleBuilder_getDescriptionField(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setDescriptionField(long jarg1, BalloonPopupStyleBuilder jarg1_, String jarg2);
  public final static native int BalloonPopupStyleBuilder_getDescriptionFontSize(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setDescriptionFontSize(long jarg1, BalloonPopupStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupStyleBuilder_getDescriptionMargins(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setDescriptionMargins(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, BalloonPopupMargins jarg2_);
  public final static native boolean BalloonPopupStyleBuilder_isDescriptionWrap(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setDescriptionWrap(long jarg1, BalloonPopupStyleBuilder jarg1_, boolean jarg2);
  public final static native long BalloonPopupStyleBuilder_getButtonMargins(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setButtonMargins(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, BalloonPopupMargins jarg2_);
  public final static native long BalloonPopupStyleBuilder_getStrokeColor(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setStrokeColor(long jarg1, BalloonPopupStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native int BalloonPopupStyleBuilder_getStrokeWidth(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setStrokeWidth(long jarg1, BalloonPopupStyleBuilder jarg1_, int jarg2);
  public final static native int BalloonPopupStyleBuilder_getTriangleWidth(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTriangleWidth(long jarg1, BalloonPopupStyleBuilder jarg1_, int jarg2);
  public final static native int BalloonPopupStyleBuilder_getTriangleHeight(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native void BalloonPopupStyleBuilder_setTriangleHeight(long jarg1, BalloonPopupStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupStyleBuilder_buildStyle(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native long BalloonPopupStyleBuilder_swigGetRawPtr(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native String BalloonPopupStyleBuilder_swigGetClassName(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native Object BalloonPopupStyleBuilder_swigGetDirectorObject(long jarg1, BalloonPopupStyleBuilder jarg1_);
  public final static native long BalloonPopupStyleBuilder_SWIGSmartPtrUpcast(long jarg1);
}
