/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.graphics.Color;
import com.carto.styles.StyleBuilder;
import com.carto.styles.BalloonPopupStyle;
import com.carto.styles.BalloonPopupButtonStyle;
import com.carto.styles.BalloonPopupMargins;

/** @hidden */
@com.carto.utils.DontObfuscate public class BalloonPopupButtonStyleBuilderModuleJNI {
  public final static native long new_BalloonPopupButtonStyleBuilder();
  public final static native void delete_BalloonPopupButtonStyleBuilder(long jarg1);
  public final static native int BalloonPopupButtonStyleBuilder_getButtonWidth(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setButtonWidth(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, int jarg2);
  public final static native int BalloonPopupButtonStyleBuilder_getCornerRadius(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setCornerRadius(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupButtonStyleBuilder_getTextColor(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setTextColor(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native String BalloonPopupButtonStyleBuilder_getTextFontName(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setTextFontName(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, String jarg2);
  public final static native int BalloonPopupButtonStyleBuilder_getTextFontSize(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setTextFontSize(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupButtonStyleBuilder_getTextMargins(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setTextMargins(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, long jarg2, BalloonPopupMargins jarg2_);
  public final static native long BalloonPopupButtonStyleBuilder_getStrokeColor(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setStrokeColor(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, long jarg2, Color jarg2_);
  public final static native int BalloonPopupButtonStyleBuilder_getStrokeWidth(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native void BalloonPopupButtonStyleBuilder_setStrokeWidth(long jarg1, BalloonPopupButtonStyleBuilder jarg1_, int jarg2);
  public final static native long BalloonPopupButtonStyleBuilder_buildStyle(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native long BalloonPopupButtonStyleBuilder_swigGetRawPtr(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native String BalloonPopupButtonStyleBuilder_swigGetClassName(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native Object BalloonPopupButtonStyleBuilder_swigGetDirectorObject(long jarg1, BalloonPopupButtonStyleBuilder jarg1_);
  public final static native long BalloonPopupButtonStyleBuilder_SWIGSmartPtrUpcast(long jarg1);
}
