/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.utils.AssetPackage;

/** @hidden */
public class CompiledStyleSetModuleJNI {
  public final static native long new_CompiledStyleSet__SWIG_0(long jarg1, AssetPackage jarg1_);
  public final static native long new_CompiledStyleSet__SWIG_1(long jarg1, AssetPackage jarg1_, String jarg2);
  public final static native void delete_CompiledStyleSet(long jarg1);
  public final static native String CompiledStyleSet_getStyleName(long jarg1, CompiledStyleSet jarg1_);
  public final static native String CompiledStyleSet_getStyleAssetName(long jarg1, CompiledStyleSet jarg1_);
  public final static native long CompiledStyleSet_getAssetPackage(long jarg1, CompiledStyleSet jarg1_);
  public final static native long CompiledStyleSet_swigGetRawPtr(long jarg1, CompiledStyleSet jarg1_);
}
