/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.styles.GeometryCollectionStyle;
import com.carto.styles.PointStyle;
import com.carto.styles.LineStyle;
import com.carto.styles.PolygonStyle;
import com.carto.styles.StyleBuilder;

/** @hidden */
@com.carto.utils.DontObfuscate public class GeometryCollectionStyleBuilderModuleJNI {
  public final static native long new_GeometryCollectionStyleBuilder();
  public final static native void delete_GeometryCollectionStyleBuilder(long jarg1);
  public final static native long GeometryCollectionStyleBuilder_getPointStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native void GeometryCollectionStyleBuilder_setPointStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_, long jarg2, PointStyle jarg2_);
  public final static native long GeometryCollectionStyleBuilder_getLineStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native void GeometryCollectionStyleBuilder_setLineStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_, long jarg2, LineStyle jarg2_);
  public final static native long GeometryCollectionStyleBuilder_getPolygonStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native void GeometryCollectionStyleBuilder_setPolygonStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_, long jarg2, PolygonStyle jarg2_);
  public final static native long GeometryCollectionStyleBuilder_buildStyle(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native long GeometryCollectionStyleBuilder_swigGetRawPtr(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native String GeometryCollectionStyleBuilder_swigGetClassName(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native Object GeometryCollectionStyleBuilder_swigGetDirectorObject(long jarg1, GeometryCollectionStyleBuilder jarg1_);
  public final static native long GeometryCollectionStyleBuilder_SWIGSmartPtrUpcast(long jarg1);
}
