/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.graphics.Color;
import com.carto.styles.BillboardStyle;

/** @hidden */
@com.carto.utils.DontObfuscate public class LabelStyleModuleJNI {
  public final static native void delete_LabelStyle(long jarg1);
  public final static native float LabelStyle_getAnchorPointX(long jarg1, LabelStyle jarg1_);
  public final static native float LabelStyle_getAnchorPointY(long jarg1, LabelStyle jarg1_);
  public final static native boolean LabelStyle_isFlippable(long jarg1, LabelStyle jarg1_);
  public final static native int LabelStyle_getOrientationMode(long jarg1, LabelStyle jarg1_);
  public final static native int LabelStyle_getScalingMode(long jarg1, LabelStyle jarg1_);
  public final static native float LabelStyle_getRenderScale(long jarg1, LabelStyle jarg1_);
  public final static native long LabelStyle_swigGetRawPtr(long jarg1, LabelStyle jarg1_);
  public final static native String LabelStyle_swigGetClassName(long jarg1, LabelStyle jarg1_);
  public final static native Object LabelStyle_swigGetDirectorObject(long jarg1, LabelStyle jarg1_);
  public final static native long LabelStyle_SWIGSmartPtrUpcast(long jarg1);
}
