/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.graphics.Bitmap;
import com.carto.graphics.Color;
import com.carto.styles.BillboardStyle;

/**
 * A style for markers. Contains attributes for configuring how the marker is drawn on the screen.
 */
@com.carto.utils.DontObfuscate public class MarkerStyle extends BillboardStyle {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public MarkerStyle(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(MarkerStyle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MarkerStyleModuleJNI.delete_MarkerStyle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.styles.MarkerStyle swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.styles.MarkerStyleModuleJNI.MarkerStyle_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.styles.MarkerStyle) director;
    }

    String objClassName = com.carto.styles.MarkerStyleModuleJNI.MarkerStyle_swigGetClassName(cPtr, null);
    com.carto.styles.MarkerStyle objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.styles." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.styles.MarkerStyle) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Returns the horizontal anchor point of the marker.<br>
 * @return The horizontal anchor point of the marker.
 */
  public float getAnchorPointX() {
    return MarkerStyleModuleJNI.MarkerStyle_getAnchorPointX(swigCPtr, this);
  }

/**
 * Returns the vertical anchor point of the marker.<br>
 * @return The vertical anchor point of the marker.
 */
  public float getAnchorPointY() {
    return MarkerStyleModuleJNI.MarkerStyle_getAnchorPointY(swigCPtr, this);
  }

/**
 * Returns the bitmap of the marker.<br>
 * @return The bitmap of the marker.
 */
  public Bitmap getBitmap() {
    long cPtr = MarkerStyleModuleJNI.MarkerStyle_getBitmap(swigCPtr, this);
    return (cPtr == 0) ? null : new Bitmap(cPtr, true);
  }

/**
 * Returns the orientation mode of the marker.<br>
 * @return The orientation mode of the marker.
 */
  public BillboardOrientation getOrientationMode() {
    return BillboardOrientation.swigToEnum(MarkerStyleModuleJNI.MarkerStyle_getOrientationMode(swigCPtr, this));
  }

/**
 * Returns the scaling mode of the marker.<br>
 * @return The scaling mode of the marker.
 */
  public BillboardScaling getScalingMode() {
    return BillboardScaling.swigToEnum(MarkerStyleModuleJNI.MarkerStyle_getScalingMode(swigCPtr, this));
  }

/**
 * Returns the click size of the marker.<br>
 * @return The click size of the marker, units depend on the scaling mode. If -1, then marker size is used.
 */
  public float getClickSize() {
    return MarkerStyleModuleJNI.MarkerStyle_getClickSize(swigCPtr, this);
  }

/**
 * Returns the size of the marker.<br>
 * @return The size of the marker, units depend on the scaling mode.
 */
  public float getSize() {
    return MarkerStyleModuleJNI.MarkerStyle_getSize(swigCPtr, this);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return MarkerStyleModuleJNI.MarkerStyle_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return MarkerStyleModuleJNI.MarkerStyle_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return MarkerStyleModuleJNI.MarkerStyle_swigGetDirectorObject(swigCPtr, this);
  }

}
