/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.graphics.Bitmap;
import com.carto.styles.BillboardStyleBuilder;
import com.carto.styles.MarkerStyle;

/** @hidden */
@com.carto.utils.DontObfuscate public class MarkerStyleBuilderModuleJNI {
  public final static native long new_MarkerStyleBuilder();
  public final static native void delete_MarkerStyleBuilder(long jarg1);
  public final static native float MarkerStyleBuilder_getAnchorPointX(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setAnchorPointX(long jarg1, MarkerStyleBuilder jarg1_, float jarg2);
  public final static native float MarkerStyleBuilder_getAnchorPointY(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setAnchorPointY(long jarg1, MarkerStyleBuilder jarg1_, float jarg2);
  public final static native void MarkerStyleBuilder_setAnchorPoint(long jarg1, MarkerStyleBuilder jarg1_, float jarg2, float jarg3);
  public final static native long MarkerStyleBuilder_getBitmap(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setBitmap(long jarg1, MarkerStyleBuilder jarg1_, long jarg2, Bitmap jarg2_);
  public final static native int MarkerStyleBuilder_getOrientationMode(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setOrientationMode(long jarg1, MarkerStyleBuilder jarg1_, int jarg2);
  public final static native int MarkerStyleBuilder_getScalingMode(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setScalingMode(long jarg1, MarkerStyleBuilder jarg1_, int jarg2);
  public final static native float MarkerStyleBuilder_getClickSize(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setClickSize(long jarg1, MarkerStyleBuilder jarg1_, float jarg2);
  public final static native float MarkerStyleBuilder_getSize(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native void MarkerStyleBuilder_setSize(long jarg1, MarkerStyleBuilder jarg1_, float jarg2);
  public final static native long MarkerStyleBuilder_buildStyle(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native long MarkerStyleBuilder_swigGetRawPtr(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native String MarkerStyleBuilder_swigGetClassName(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native Object MarkerStyleBuilder_swigGetDirectorObject(long jarg1, MarkerStyleBuilder jarg1_);
  public final static native long MarkerStyleBuilder_SWIGSmartPtrUpcast(long jarg1);
}
