/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.styles.PolygonStyle;
import com.carto.styles.StyleBuilder;

/** @hidden */
@com.carto.utils.DontObfuscate public class PolygonStyleBuilderModuleJNI {
  public final static native long new_PolygonStyleBuilder();
  public final static native void delete_PolygonStyleBuilder(long jarg1);
  public final static native long PolygonStyleBuilder_getLineStyle(long jarg1, PolygonStyleBuilder jarg1_);
  public final static native void PolygonStyleBuilder_setLineStyle(long jarg1, PolygonStyleBuilder jarg1_, long jarg2, LineStyle jarg2_);
  public final static native long PolygonStyleBuilder_buildStyle(long jarg1, PolygonStyleBuilder jarg1_);
  public final static native long PolygonStyleBuilder_swigGetRawPtr(long jarg1, PolygonStyleBuilder jarg1_);
  public final static native String PolygonStyleBuilder_swigGetClassName(long jarg1, PolygonStyleBuilder jarg1_);
  public final static native Object PolygonStyleBuilder_swigGetDirectorObject(long jarg1, PolygonStyleBuilder jarg1_);
  public final static native long PolygonStyleBuilder_SWIGSmartPtrUpcast(long jarg1);
}
