/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.styles;

import com.carto.styles.BillboardStyleBuilder;
import com.carto.styles.PopupStyle;

/** @hidden */
@com.carto.utils.DontObfuscate public class PopupStyleBuilderModuleJNI {
  public final static native long new_PopupStyleBuilder();
  public final static native void delete_PopupStyleBuilder(long jarg1);
  public final static native long PopupStyleBuilder_buildStyle(long jarg1, PopupStyleBuilder jarg1_);
  public final static native long PopupStyleBuilder_swigGetRawPtr(long jarg1, PopupStyleBuilder jarg1_);
  public final static native String PopupStyleBuilder_swigGetClassName(long jarg1, PopupStyleBuilder jarg1_);
  public final static native Object PopupStyleBuilder_swigGetDirectorObject(long jarg1, PopupStyleBuilder jarg1_);
  public final static native long PopupStyleBuilder_SWIGSmartPtrUpcast(long jarg1);
}
