/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.graphics;

/** @hidden */
public class ColorModuleJNI {
  public final static native long new_Color__SWIG_0();
  public final static native long new_Color__SWIG_1(short jarg1, short jarg2, short jarg3, short jarg4);
  public final static native long new_Color__SWIG_2(int jarg1);
  public final static native boolean Color_equalsInternal(long jarg1, Color jarg1_, long jarg2, Color jarg2_);
  public final static native short Color_getR(long jarg1, Color jarg1_);
  public final static native short Color_getG(long jarg1, Color jarg1_);
  public final static native short Color_getB(long jarg1, Color jarg1_);
  public final static native short Color_getA(long jarg1, Color jarg1_);
  public final static native int Color_getARGB(long jarg1, Color jarg1_);
  public final static native int Color_hashCodeInternal(long jarg1, Color jarg1_);
  public final static native String Color_toString(long jarg1, Color jarg1_);
  public final static native long Color_swigGetRawPtr(long jarg1, Color jarg1_);
  public final static native void delete_Color(long jarg1);
}
