/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.routing;

import com.carto.routing.RoutingService;
import com.carto.routing.RoutingRequest;
import com.carto.routing.RoutingResult;
import com.carto.routing.RouteMatchingRequest;
import com.carto.routing.RouteMatchingResult;

/**
 * An offline routing service that uses Carto-specific routing <br>
 * database file created from OSRM prepared routing files.<br>
 * Note: this class is experimental and may change or even be removed in future SDK versions.
 */
@com.carto.utils.DontObfuscate public class OSRMOfflineRoutingService extends RoutingService {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public OSRMOfflineRoutingService(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(OSRMOfflineRoutingService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OSRMOfflineRoutingServiceModuleJNI.delete_OSRMOfflineRoutingService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.routing.OSRMOfflineRoutingService swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.routing.OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.routing.OSRMOfflineRoutingService) director;
    }

    String objClassName = com.carto.routing.OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_swigGetClassName(cPtr, null);
    com.carto.routing.OSRMOfflineRoutingService objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.routing." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.routing.OSRMOfflineRoutingService) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a new OSRMOfflineRoutingService instance given database file.<br>
 * @param path The full path to the database file.<br>
 * @throws java.lang.Exception If the database file could not be opened or read.
 */
  public OSRMOfflineRoutingService(String path) throws java.io.IOException {
    this(OSRMOfflineRoutingServiceModuleJNI.new_OSRMOfflineRoutingService(path), true);
    OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public String getProfile() {
    return (getClass() == OSRMOfflineRoutingService.class) ? OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_getProfile(swigCPtr, this) : OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_getProfileSwigExplicitOSRMOfflineRoutingService(swigCPtr, this);
  }

  public void setProfile(String profile) {
    if (getClass() == OSRMOfflineRoutingService.class) OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_setProfile(swigCPtr, this, profile); else OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_setProfileSwigExplicitOSRMOfflineRoutingService(swigCPtr, this, profile);
  }

  public RouteMatchingResult matchRoute(RouteMatchingRequest request) throws java.io.IOException {
    long cPtr = (getClass() == OSRMOfflineRoutingService.class) ? OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_matchRoute(swigCPtr, this, RouteMatchingRequest.getCPtr(request), request) : OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_matchRouteSwigExplicitOSRMOfflineRoutingService(swigCPtr, this, RouteMatchingRequest.getCPtr(request), request);
    return (cPtr == 0) ? null : new RouteMatchingResult(cPtr, true);
  }

  public RoutingResult calculateRoute(RoutingRequest request) throws java.io.IOException {
    long cPtr = (getClass() == OSRMOfflineRoutingService.class) ? OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_calculateRoute(swigCPtr, this, RoutingRequest.getCPtr(request), request) : OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_calculateRouteSwigExplicitOSRMOfflineRoutingService(swigCPtr, this, RoutingRequest.getCPtr(request), request);
    return (cPtr == 0) ? null : new RoutingResult(cPtr, true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return OSRMOfflineRoutingServiceModuleJNI.OSRMOfflineRoutingService_swigGetDirectorObject(swigCPtr, this);
  }

}
