/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.routing;

public class RoutingInstructionVector {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public RoutingInstructionVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(RoutingInstructionVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RoutingInstructionModuleJNI.delete_RoutingInstructionVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RoutingInstructionVector() {
    this(RoutingInstructionModuleJNI.new_RoutingInstructionVector__SWIG_0(), true);
  }

  public RoutingInstructionVector(long n) {
    this(RoutingInstructionModuleJNI.new_RoutingInstructionVector__SWIG_1(n), true);
  }

  public long size() {
    return RoutingInstructionModuleJNI.RoutingInstructionVector_size(swigCPtr, this);
  }

  public long capacity() {
    return RoutingInstructionModuleJNI.RoutingInstructionVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    RoutingInstructionModuleJNI.RoutingInstructionVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return RoutingInstructionModuleJNI.RoutingInstructionVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    RoutingInstructionModuleJNI.RoutingInstructionVector_clear(swigCPtr, this);
  }

  public void add(RoutingInstruction x) {
    RoutingInstructionModuleJNI.RoutingInstructionVector_add(swigCPtr, this, RoutingInstruction.getCPtr(x), x);
  }

  public RoutingInstruction get(int i) { return new RoutingInstruction(RoutingInstructionModuleJNI.RoutingInstructionVector_get(swigCPtr, this, i), true); }

  public void set(int i, RoutingInstruction val) {
    RoutingInstructionModuleJNI.RoutingInstructionVector_set(swigCPtr, this, i, RoutingInstruction.getCPtr(val), val);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return RoutingInstructionModuleJNI.RoutingInstructionVector_swigGetRawPtr(swigCPtr, this);
  }

}
