/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.routing;

/**
 * Route matching point type.
 */
public enum RouteMatchingPointType {
/**
 * The point was unmatched.
 */
  ROUTE_MATCHING_POINT_UNMATCHED,
/**
 * The point was interpolated.
 */
  ROUTE_MATCHING_POINT_INTERPOLATED,
/**
 * The point was matched.
 */
  ROUTE_MATCHING_POINT_MATCHED;

  public final int swigValue() {
    return swigValue;
  }

  public static RouteMatchingPointType swigToEnum(int swigValue) {
    RouteMatchingPointType[] swigValues = RouteMatchingPointType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (RouteMatchingPointType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + RouteMatchingPointType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private RouteMatchingPointType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private RouteMatchingPointType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private RouteMatchingPointType(RouteMatchingPointType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

