/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.routing;

import com.carto.core.MapPos;
import com.carto.core.MapPosVector;
import com.carto.projections.Projection;
import com.carto.routing.RouteMatchingPoint;
import com.carto.routing.RouteMatchingEdge;

/**
 * A class that defines list of matching points from road network.
 */
public class RouteMatchingResult {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public RouteMatchingResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(RouteMatchingResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RouteMatchingResultModuleJNI.delete_RouteMatchingResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Checks if this object is equal to the specified object.
   * @param obj The reference object.
   * @return True when objects are equal, false otherwise.
   */
  public boolean equals(Object obj) {
    if (obj instanceof RouteMatchingResult) {
      return ((RouteMatchingResult)obj).swigGetRawPtr() == swigGetRawPtr();
    }
    return false;
  }

  /**
   * Returns the hash value of this object.
   * @return The hash value of this object.
   */
  public int hashCode() {
    return (int)swigGetRawPtr();
  }


/**
 * Constructs a new RouteMatchingResult instance from projection and matched points.<br>
 * @param projection The projection of the routing result (same as the request).<br>
 * @param matchingPoints The matched points corresponding to the requested points snapped to road network.<br>
 * @param matchingEdges The matched edges that are referenced through matching points.
 */
  public RouteMatchingResult(Projection projection, RouteMatchingPointVector matchingPoints, RouteMatchingEdgeVector matchingEdges) {
    this(RouteMatchingResultModuleJNI.new_RouteMatchingResult(Projection.getCPtr(projection), projection, RouteMatchingPointVector.getCPtr(matchingPoints), matchingPoints, RouteMatchingEdgeVector.getCPtr(matchingEdges), matchingEdges), true);
  }

/**
 * Returns the projection of the points in the result.<br>
 * @return The projection of the result.
 */
  public Projection getProjection() {
  long cPtr = RouteMatchingResultModuleJNI.RouteMatchingResult_getProjection(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.projections.Projection.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the point list of the result. The list contains all the points from the request snapped to the road network.<br>
 * @return The point list of the result.
 */
  public MapPosVector getPoints() { return new MapPosVector(RouteMatchingResultModuleJNI.RouteMatchingResult_getPoints(swigCPtr, this), true); }

/**
 * Returns the list with details of the matched edges.<br>
 * @return The list with details of the matched edges.
 */
  public RouteMatchingEdgeVector getMatchingEdges() { return new RouteMatchingEdgeVector(RouteMatchingResultModuleJNI.RouteMatchingResult_getMatchingEdges(swigCPtr, this), true); }

/**
 * Returns the list with details of the matched points.<br>
 * @return The list with details of the matched points.
 */
  public RouteMatchingPointVector getMatchingPoints() { return new RouteMatchingPointVector(RouteMatchingResultModuleJNI.RouteMatchingResult_getMatchingPoints(swigCPtr, this), true); }

/**
 * Creates a string representation of this result object, useful for logging.<br>
 * @return The string representation of this result object.
 */
  public String toString() {
    return RouteMatchingResultModuleJNI.RouteMatchingResult_toString(swigCPtr, this);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return RouteMatchingResultModuleJNI.RouteMatchingResult_swigGetRawPtr(swigCPtr, this);
  }

}
