/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.routing;

import com.carto.core.Variant;
import com.carto.geometry.FeatureCollection;
import com.carto.projections.Projection;
import com.carto.routing.RoutingService;
import com.carto.routing.RoutingRequest;
import com.carto.routing.RoutingResult;
import com.carto.routing.RouteMatchingRequest;
import com.carto.routing.RouteMatchingResult;

/**
 * An offline routing service that uses SGRE routing engine.<br>
 * Note: this class is experimental and may change or even be removed in future SDK versions.
 */
@com.carto.utils.DontObfuscate public class SGREOfflineRoutingService extends RoutingService {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public SGREOfflineRoutingService(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(SGREOfflineRoutingService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SGREOfflineRoutingServiceModuleJNI.delete_SGREOfflineRoutingService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.routing.SGREOfflineRoutingService swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.routing.SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.routing.SGREOfflineRoutingService) director;
    }

    String objClassName = com.carto.routing.SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_swigGetClassName(cPtr, null);
    com.carto.routing.SGREOfflineRoutingService objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.routing." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.routing.SGREOfflineRoutingService) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a new SGREOfflineRoutingService instance from a given GeoJSON and rule list.<br>
 * @param geoJSON The GeoJSON variant specifying features used for the routing graph.<br>
 * @param config A configuration specifying various routing metrics and rules.<br>
 * @throws java.lang.Exception If an error occured during rule list parsing.
 */
  public SGREOfflineRoutingService(Variant geoJSON, Variant config) throws java.io.IOException {
    this(SGREOfflineRoutingServiceModuleJNI.new_SGREOfflineRoutingService__SWIG_0(Variant.getCPtr(geoJSON), geoJSON, Variant.getCPtr(config), config), true);
    SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Constructs a new SGREOfflineRoutingService instance from a given feature collection and rule list.<br>
 * @param projection Projection for the features in featureCollection. Can be null if the coordinates are based on WGS84.<br>
 * @param featureCollection The feature collection used for the routing graph.<br>
 * @param config A configuration specifying various routing metrics and rules.<br>
 * @throws java.lang.Exception If an error occured during rule list parsing.
 */
  public SGREOfflineRoutingService(Projection projection, FeatureCollection featureCollection, Variant config) throws java.io.IOException {
    this(SGREOfflineRoutingServiceModuleJNI.new_SGREOfflineRoutingService__SWIG_1(Projection.getCPtr(projection), projection, FeatureCollection.getCPtr(featureCollection), featureCollection, Variant.getCPtr(config), config), true);
    SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Returns the value of specified routing parameter.<br>
 * @param param The name of the parameter. For example "$speed".<br>
 * @return The value of the parameter. If the parameter does not exist, NaN is returned.
 */
  public float getRoutingParameter(String param) {
    return SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_getRoutingParameter(swigCPtr, this, param);
  }

/**
 * Sets the value of specified routing parameter.<br>
 * @param param The name of the parameter. For example "$speed".<br>
 * @param value The new value of the parameter.
 */
  public void setRoutingParameter(String param, float value) {
    SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_setRoutingParameter(swigCPtr, this, param, value);
  }

  public String getProfile() {
    return (getClass() == SGREOfflineRoutingService.class) ? SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_getProfile(swigCPtr, this) : SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_getProfileSwigExplicitSGREOfflineRoutingService(swigCPtr, this);
  }

  public void setProfile(String profile) {
    if (getClass() == SGREOfflineRoutingService.class) SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_setProfile(swigCPtr, this, profile); else SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_setProfileSwigExplicitSGREOfflineRoutingService(swigCPtr, this, profile);
  }

  public RouteMatchingResult matchRoute(RouteMatchingRequest request) throws java.io.IOException {
    long cPtr = (getClass() == SGREOfflineRoutingService.class) ? SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_matchRoute(swigCPtr, this, RouteMatchingRequest.getCPtr(request), request) : SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_matchRouteSwigExplicitSGREOfflineRoutingService(swigCPtr, this, RouteMatchingRequest.getCPtr(request), request);
    return (cPtr == 0) ? null : new RouteMatchingResult(cPtr, true);
  }

  public RoutingResult calculateRoute(RoutingRequest request) throws java.io.IOException {
    long cPtr = (getClass() == SGREOfflineRoutingService.class) ? SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_calculateRoute(swigCPtr, this, RoutingRequest.getCPtr(request), request) : SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_calculateRouteSwigExplicitSGREOfflineRoutingService(swigCPtr, this, RoutingRequest.getCPtr(request), request);
    return (cPtr == 0) ? null : new RoutingResult(cPtr, true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return SGREOfflineRoutingServiceModuleJNI.SGREOfflineRoutingService_swigGetDirectorObject(swigCPtr, this);
  }

}
