/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.routing;

import com.carto.routing.RoutingService;
import com.carto.routing.RoutingRequest;
import com.carto.routing.RoutingResult;
import com.carto.routing.RouteMatchingRequest;
import com.carto.routing.RouteMatchingResult;

/** @hidden */
@com.carto.utils.DontObfuscate public class ValhallaOnlineRoutingServiceModuleJNI {
  public final static native long new_ValhallaOnlineRoutingService(String jarg1);
  public final static native void delete_ValhallaOnlineRoutingService(long jarg1);
  public final static native String ValhallaOnlineRoutingService_getCustomServiceURL(long jarg1, ValhallaOnlineRoutingService jarg1_);
  public final static native void ValhallaOnlineRoutingService_setCustomServiceURL(long jarg1, ValhallaOnlineRoutingService jarg1_, String jarg2);
  public final static native String ValhallaOnlineRoutingService_getProfile(long jarg1, ValhallaOnlineRoutingService jarg1_);
  public final static native String ValhallaOnlineRoutingService_getProfileSwigExplicitValhallaOnlineRoutingService(long jarg1, ValhallaOnlineRoutingService jarg1_);
  public final static native void ValhallaOnlineRoutingService_setProfile(long jarg1, ValhallaOnlineRoutingService jarg1_, String jarg2);
  public final static native void ValhallaOnlineRoutingService_setProfileSwigExplicitValhallaOnlineRoutingService(long jarg1, ValhallaOnlineRoutingService jarg1_, String jarg2);
  public final static native long ValhallaOnlineRoutingService_matchRoute(long jarg1, ValhallaOnlineRoutingService jarg1_, long jarg2, RouteMatchingRequest jarg2_) throws java.io.IOException;
  public final static native long ValhallaOnlineRoutingService_matchRouteSwigExplicitValhallaOnlineRoutingService(long jarg1, ValhallaOnlineRoutingService jarg1_, long jarg2, RouteMatchingRequest jarg2_) throws java.io.IOException;
  public final static native long ValhallaOnlineRoutingService_calculateRoute(long jarg1, ValhallaOnlineRoutingService jarg1_, long jarg2, RoutingRequest jarg2_) throws java.io.IOException;
  public final static native long ValhallaOnlineRoutingService_calculateRouteSwigExplicitValhallaOnlineRoutingService(long jarg1, ValhallaOnlineRoutingService jarg1_, long jarg2, RoutingRequest jarg2_) throws java.io.IOException;
  public final static native long ValhallaOnlineRoutingService_swigGetRawPtr(long jarg1, ValhallaOnlineRoutingService jarg1_);
  public final static native String ValhallaOnlineRoutingService_swigGetClassName(long jarg1, ValhallaOnlineRoutingService jarg1_);
  public final static native Object ValhallaOnlineRoutingService_swigGetDirectorObject(long jarg1, ValhallaOnlineRoutingService jarg1_);
  public final static native void ValhallaOnlineRoutingService_director_connect(ValhallaOnlineRoutingService obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ValhallaOnlineRoutingService_change_ownership(ValhallaOnlineRoutingService obj, long cptr, boolean take_or_release);
  public final static native long ValhallaOnlineRoutingService_SWIGSmartPtrUpcast(long jarg1);

  public static String SwigDirector_ValhallaOnlineRoutingService_getProfile(ValhallaOnlineRoutingService self) {
    return self.getProfile();
  }
  public static void SwigDirector_ValhallaOnlineRoutingService_setProfile(ValhallaOnlineRoutingService self, String profile) {
    self.setProfile(profile);
  }
  public static long SwigDirector_ValhallaOnlineRoutingService_matchRoute(ValhallaOnlineRoutingService self, long request) throws java.io.IOException {
    return RouteMatchingResult.getCPtr(self.matchRoute(new RouteMatchingRequest(request, true)));
  }
  public static long SwigDirector_ValhallaOnlineRoutingService_calculateRoute(ValhallaOnlineRoutingService self, long request) throws java.io.IOException {
    return RoutingResult.getCPtr(self.calculateRoute(new RoutingRequest(request, true)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
