/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.layers;

import com.carto.core.MapPos;
import com.carto.vectorelements.VectorElement;
import com.carto.vectorelements.VectorElementVector;

/**
 * A special callback interface for building cluster elements from set of existing vector element.
 */
@com.carto.utils.DontObfuscate public class ClusterElementBuilder {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public ClusterElementBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(ClusterElementBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ClusterElementBuilderModuleJNI.delete_ClusterElementBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ClusterElementBuilderModuleJNI.ClusterElementBuilder_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ClusterElementBuilderModuleJNI.ClusterElementBuilder_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.layers.ClusterElementBuilder swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.layers.ClusterElementBuilderModuleJNI.ClusterElementBuilder_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.layers.ClusterElementBuilder) director;
    }

    String objClassName = com.carto.layers.ClusterElementBuilderModuleJNI.ClusterElementBuilder_swigGetClassName(cPtr, null);
    com.carto.layers.ClusterElementBuilder objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.layers." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.layers.ClusterElementBuilder) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Returns the builder mode. The return value of this method determines which builder method is called.<br>
 * @return The builder mode that determines which buildClusterElement method is called.
 */
  public ClusterBuilderMode getBuilderMode() {
    return ClusterBuilderMode.swigToEnum((getClass() == ClusterElementBuilder.class) ? ClusterElementBuilderModuleJNI.ClusterElementBuilder_getBuilderMode(swigCPtr, this) : ClusterElementBuilderModuleJNI.ClusterElementBuilder_getBuilderModeSwigExplicitClusterElementBuilder(swigCPtr, this));
  }

/**
 * A callback for building a new cluster element given position and the number of cluster element.<br>
 * @param mapPos The position of the cluster element.<br>
 * @param elementCount The number of elements in the cluster.<br>
 * @return The created cluster element.
 */
  public VectorElement buildClusterElement(MapPos mapPos, int elementCount) {
  long cPtr = (getClass() == ClusterElementBuilder.class) ? ClusterElementBuilderModuleJNI.ClusterElementBuilder_buildClusterElement__SWIG_0(swigCPtr, this, MapPos.getCPtr(mapPos), mapPos, elementCount) : ClusterElementBuilderModuleJNI.ClusterElementBuilder_buildClusterElementSwigExplicitClusterElementBuilder__SWIG_0(swigCPtr, this, MapPos.getCPtr(mapPos), mapPos, elementCount);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * A callback for building a new cluster element given position and list of vector elements.<br>
 * @param mapPos The position of the cluster element.<br>
 * @param elements The list of elements that defines the cluster.<br>
 * @return The created cluster element.
 */
  public VectorElement buildClusterElement(MapPos mapPos, VectorElementVector elements) {
  long cPtr = (getClass() == ClusterElementBuilder.class) ? ClusterElementBuilderModuleJNI.ClusterElementBuilder_buildClusterElement__SWIG_1(swigCPtr, this, MapPos.getCPtr(mapPos), mapPos, VectorElementVector.getCPtr(elements), elements) : ClusterElementBuilderModuleJNI.ClusterElementBuilder_buildClusterElementSwigExplicitClusterElementBuilder__SWIG_1(swigCPtr, this, MapPos.getCPtr(mapPos), mapPos, VectorElementVector.getCPtr(elements), elements);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return ClusterElementBuilderModuleJNI.ClusterElementBuilder_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return ClusterElementBuilderModuleJNI.ClusterElementBuilder_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return ClusterElementBuilderModuleJNI.ClusterElementBuilder_swigGetDirectorObject(swigCPtr, this);
  }

  public ClusterElementBuilder() {
    this(ClusterElementBuilderModuleJNI.new_ClusterElementBuilder(), true);
    ClusterElementBuilderModuleJNI.ClusterElementBuilder_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
