/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.layers;

import com.carto.ui.RasterTileClickInfo;

/**
 * Listener for raster tile element events like clicks etc.
 */
@com.carto.utils.DontObfuscate public class RasterTileEventListener {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public RasterTileEventListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(RasterTileEventListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RasterTileEventListenerModuleJNI.delete_RasterTileEventListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RasterTileEventListenerModuleJNI.RasterTileEventListener_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RasterTileEventListenerModuleJNI.RasterTileEventListener_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.layers.RasterTileEventListener swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.layers.RasterTileEventListenerModuleJNI.RasterTileEventListener_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.layers.RasterTileEventListener) director;
    }

    String objClassName = com.carto.layers.RasterTileEventListenerModuleJNI.RasterTileEventListener_swigGetClassName(cPtr, null);
    com.carto.layers.RasterTileEventListener objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.layers." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.layers.RasterTileEventListener) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Listener method that gets called when a click is performed on a raster tile.<br>
 * This method will NOT be called from the main thread.<br>
 * @param clickInfo A container that provides information about the click.<br>
 * @return True if the click is handled and subsequent elements should not be handled. False if the next element should be called.
 */
  public boolean onRasterTileClicked(RasterTileClickInfo clickInfo) {
    return (getClass() == RasterTileEventListener.class) ? RasterTileEventListenerModuleJNI.RasterTileEventListener_onRasterTileClicked(swigCPtr, this, RasterTileClickInfo.getCPtr(clickInfo), clickInfo) : RasterTileEventListenerModuleJNI.RasterTileEventListener_onRasterTileClickedSwigExplicitRasterTileEventListener(swigCPtr, this, RasterTileClickInfo.getCPtr(clickInfo), clickInfo);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return RasterTileEventListenerModuleJNI.RasterTileEventListener_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return RasterTileEventListenerModuleJNI.RasterTileEventListener_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return RasterTileEventListenerModuleJNI.RasterTileEventListener_swigGetDirectorObject(swigCPtr, this);
  }

  public RasterTileEventListener() {
    this(RasterTileEventListenerModuleJNI.new_RasterTileEventListener(), true);
    RasterTileEventListenerModuleJNI.RasterTileEventListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
