/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.layers;

/**
 * Interface for monitoring tile loading events.
 */
@com.carto.utils.DontObfuscate public class TileLoadListener {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public TileLoadListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(TileLoadListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TileLoadListenerModuleJNI.delete_TileLoadListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    TileLoadListenerModuleJNI.TileLoadListener_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    TileLoadListenerModuleJNI.TileLoadListener_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.layers.TileLoadListener swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.layers.TileLoadListenerModuleJNI.TileLoadListener_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.layers.TileLoadListener) director;
    }

    String objClassName = com.carto.layers.TileLoadListenerModuleJNI.TileLoadListener_swigGetClassName(cPtr, null);
    com.carto.layers.TileLoadListener objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.layers." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.layers.TileLoadListener) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Listener method that gets called when all visible raster tiles have finished loading.
 */
  public void onVisibleTilesLoaded() {
    if (getClass() == TileLoadListener.class) TileLoadListenerModuleJNI.TileLoadListener_onVisibleTilesLoaded(swigCPtr, this); else TileLoadListenerModuleJNI.TileLoadListener_onVisibleTilesLoadedSwigExplicitTileLoadListener(swigCPtr, this);
  }

/**
 * Listener method that gets called when all preloading raster tiles have finished loading.<br>
 * This method gets called after onVisibleTilesLoaded() and only if preloading is enabled.
 */
  public void onPreloadingTilesLoaded() {
    if (getClass() == TileLoadListener.class) TileLoadListenerModuleJNI.TileLoadListener_onPreloadingTilesLoaded(swigCPtr, this); else TileLoadListenerModuleJNI.TileLoadListener_onPreloadingTilesLoadedSwigExplicitTileLoadListener(swigCPtr, this);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return TileLoadListenerModuleJNI.TileLoadListener_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return TileLoadListenerModuleJNI.TileLoadListener_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return TileLoadListenerModuleJNI.TileLoadListener_swigGetDirectorObject(swigCPtr, this);
  }

  public TileLoadListener() {
    this(TileLoadListenerModuleJNI.new_TileLoadListener(), true);
    TileLoadListenerModuleJNI.TileLoadListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
