/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.layers;

/**
 * Vector tile rendering order.
 */
public enum VectorTileRenderOrder {
/**
 * No rendering, elements are hidden.
 */
  VECTOR_TILE_RENDER_ORDER_HIDDEN(VectorTileLayerModuleJNI.VECTOR_TILE_RENDER_ORDER_HIDDEN_get()),
/**
 * Elements are rendered together with the same layer elements.<br>
 * Layers that are on top of the layers are rendered on top this layer.
 */
  VECTOR_TILE_RENDER_ORDER_LAYER(VectorTileLayerModuleJNI.VECTOR_TILE_RENDER_ORDER_LAYER_get()),
/**
 * Elements are rendered on top of all normal layers.
 */
  VECTOR_TILE_RENDER_ORDER_LAST(VectorTileLayerModuleJNI.VECTOR_TILE_RENDER_ORDER_LAST_get());

  public final int swigValue() {
    return swigValue;
  }

  public static VectorTileRenderOrder swigToEnum(int swigValue) {
    VectorTileRenderOrder[] swigValues = VectorTileRenderOrder.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (VectorTileRenderOrder swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + VectorTileRenderOrder.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private VectorTileRenderOrder() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private VectorTileRenderOrder(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private VectorTileRenderOrder(VectorTileRenderOrder swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

