/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.layers;

import com.carto.core.ScreenPos;
import com.carto.geometry.Geometry;
import com.carto.vectorelements.VectorElement;
import com.carto.styles.PointStyle;
import com.carto.ui.VectorElementDragInfo;

/** @hidden */
@com.carto.utils.DontObfuscate public class VectorEditEventListenerModuleJNI {
  public final static native void delete_VectorEditEventListener(long jarg1);
  public final static native boolean VectorEditEventListener_onElementSelect(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_);
  public final static native boolean VectorEditEventListener_onElementSelectSwigExplicitVectorEditEventListener(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_);
  public final static native void VectorEditEventListener_onElementDeselected(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_);
  public final static native void VectorEditEventListener_onElementDeselectedSwigExplicitVectorEditEventListener(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_);
  public final static native void VectorEditEventListener_onElementModify(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_, long jarg3, Geometry jarg3_);
  public final static native void VectorEditEventListener_onElementDelete(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_);
  public final static native int VectorEditEventListener_onDragStart(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElementDragInfo jarg2_);
  public final static native int VectorEditEventListener_onDragStartSwigExplicitVectorEditEventListener(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElementDragInfo jarg2_);
  public final static native int VectorEditEventListener_onDragMove(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElementDragInfo jarg2_);
  public final static native int VectorEditEventListener_onDragMoveSwigExplicitVectorEditEventListener(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElementDragInfo jarg2_);
  public final static native int VectorEditEventListener_onDragEnd(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElementDragInfo jarg2_);
  public final static native int VectorEditEventListener_onDragEndSwigExplicitVectorEditEventListener(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElementDragInfo jarg2_);
  public final static native long VectorEditEventListener_onSelectDragPointStyle(long jarg1, VectorEditEventListener jarg1_, long jarg2, VectorElement jarg2_, int jarg3);
  public final static native long VectorEditEventListener_swigGetRawPtr(long jarg1, VectorEditEventListener jarg1_);
  public final static native String VectorEditEventListener_swigGetClassName(long jarg1, VectorEditEventListener jarg1_);
  public final static native Object VectorEditEventListener_swigGetDirectorObject(long jarg1, VectorEditEventListener jarg1_);
  public final static native long new_VectorEditEventListener();
  public final static native void VectorEditEventListener_director_connect(VectorEditEventListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void VectorEditEventListener_change_ownership(VectorEditEventListener obj, long cptr, boolean take_or_release);

  public static boolean SwigDirector_VectorEditEventListener_onElementSelect(VectorEditEventListener self, long element) {
    return self.onElementSelect(
  /** @hidden */
  com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(element, true)
);
  }
  public static void SwigDirector_VectorEditEventListener_onElementDeselected(VectorEditEventListener self, long element) {
    self.onElementDeselected(
  /** @hidden */
  com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(element, true)
);
  }
  public static void SwigDirector_VectorEditEventListener_onElementModify(VectorEditEventListener self, long element, long geometry) {
    self.onElementModify(
  /** @hidden */
  com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(element, true)
, 
  /** @hidden */
  com.carto.geometry.Geometry.swigCreatePolymorphicInstance(geometry, true)
);
  }
  public static void SwigDirector_VectorEditEventListener_onElementDelete(VectorEditEventListener self, long element) {
    self.onElementDelete(
  /** @hidden */
  com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(element, true)
);
  }
  public static int SwigDirector_VectorEditEventListener_onDragStart(VectorEditEventListener self, long dragInfo) {
    return (self.onDragStart(new VectorElementDragInfo(dragInfo, true))).swigValue();
  }
  public static int SwigDirector_VectorEditEventListener_onDragMove(VectorEditEventListener self, long dragInfo) {
    return (self.onDragMove(new VectorElementDragInfo(dragInfo, true))).swigValue();
  }
  public static int SwigDirector_VectorEditEventListener_onDragEnd(VectorEditEventListener self, long dragInfo) {
    return (self.onDragEnd(new VectorElementDragInfo(dragInfo, true))).swigValue();
  }
  public static long SwigDirector_VectorEditEventListener_onSelectDragPointStyle(VectorEditEventListener self, long element, int dragPointStyle) {
    return PointStyle.getCPtr(self.onSelectDragPointStyle(
  /** @hidden */
  com.carto.vectorelements.VectorElement.swigCreatePolymorphicInstance(element, true)
, VectorElementDragPointStyle.swigToEnum(dragPointStyle)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
