/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.layers;

import com.carto.ui.VectorElementClickInfo;

/** @hidden */
@com.carto.utils.DontObfuscate public class VectorElementEventListenerModuleJNI {
  public final static native void delete_VectorElementEventListener(long jarg1);
  public final static native boolean VectorElementEventListener_onVectorElementClicked(long jarg1, VectorElementEventListener jarg1_, long jarg2, VectorElementClickInfo jarg2_);
  public final static native boolean VectorElementEventListener_onVectorElementClickedSwigExplicitVectorElementEventListener(long jarg1, VectorElementEventListener jarg1_, long jarg2, VectorElementClickInfo jarg2_);
  public final static native long VectorElementEventListener_swigGetRawPtr(long jarg1, VectorElementEventListener jarg1_);
  public final static native String VectorElementEventListener_swigGetClassName(long jarg1, VectorElementEventListener jarg1_);
  public final static native Object VectorElementEventListener_swigGetDirectorObject(long jarg1, VectorElementEventListener jarg1_);
  public final static native long new_VectorElementEventListener();
  public final static native void VectorElementEventListener_director_connect(VectorElementEventListener obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void VectorElementEventListener_change_ownership(VectorElementEventListener obj, long cptr, boolean take_or_release);

  public static boolean SwigDirector_VectorElementEventListener_onVectorElementClicked(VectorElementEventListener self, long clickInfo) {
    return self.onVectorElementClicked(new VectorElementClickInfo(clickInfo, true));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
