/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geocoding;

import com.carto.core.Address;
import com.carto.core.StringVector;

/**
 * A geographical address describing country, region, county and other information.
 */
public class GeocodingAddress extends Address {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public GeocodingAddress(long cPtr, boolean cMemoryOwn) {
    super(GeocodingAddressModuleJNI.GeocodingAddress_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(GeocodingAddress obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        GeocodingAddressModuleJNI.delete_GeocodingAddress(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

/**
 * Constructs an empty Address object.
 */
  public GeocodingAddress() {
    this(GeocodingAddressModuleJNI.new_GeocodingAddress__SWIG_0(), true);
  }

/**
 * Constructs a new address from the the country, region, county and other attributes.<br>
 * @param country The country name of the address.<br>
 * @param region The region name of the address.<br>
 * @param county The county name of the address.<br>
 * @param locality The locality name of the address.<br>
 * @param neighbourhood The neighbourhood name of the address.<br>
 * @param street The street name of the address.<br>
 * @param postcode The postcode of the address.<br>
 * @param houseNumber The house number of the address.<br>
 * @param name The name of the address.<br>
 * @param categories The category tags describing the address.
 */
  public GeocodingAddress(String country, String region, String county, String locality, String neighbourhood, String street, String postcode, String houseNumber, String name, StringVector categories) {
    this(GeocodingAddressModuleJNI.new_GeocodingAddress__SWIG_1(country, region, county, locality, neighbourhood, street, postcode, houseNumber, name, StringVector.getCPtr(categories), categories), true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return GeocodingAddressModuleJNI.GeocodingAddress_swigGetRawPtr(swigCPtr, this);
  }

}
