/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geocoding;

import com.carto.core.MapPos;
import com.carto.core.Variant;
import com.carto.projections.Projection;

/** @hidden */
public class GeocodingRequestModuleJNI {
  public final static native long new_GeocodingRequest(long jarg1, Projection jarg1_, String jarg2);
  public final static native void delete_GeocodingRequest(long jarg1);
  public final static native String GeocodingRequest_getQuery(long jarg1, GeocodingRequest jarg1_);
  public final static native long GeocodingRequest_getProjection(long jarg1, GeocodingRequest jarg1_);
  public final static native long GeocodingRequest_getLocation(long jarg1, GeocodingRequest jarg1_);
  public final static native void GeocodingRequest_setLocation(long jarg1, GeocodingRequest jarg1_, long jarg2, MapPos jarg2_);
  public final static native float GeocodingRequest_getLocationRadius(long jarg1, GeocodingRequest jarg1_);
  public final static native void GeocodingRequest_setLocationRadius(long jarg1, GeocodingRequest jarg1_, float jarg2);
  public final static native long GeocodingRequest_getCustomParameter(long jarg1, GeocodingRequest jarg1_, String jarg2);
  public final static native void GeocodingRequest_setCustomParameter(long jarg1, GeocodingRequest jarg1_, String jarg2, long jarg3, Variant jarg3_);
  public final static native String GeocodingRequest_toString(long jarg1, GeocodingRequest jarg1_);
  public final static native long GeocodingRequest_swigGetRawPtr(long jarg1, GeocodingRequest jarg1_);
}
