/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geocoding;

import com.carto.geocoding.GeocodingService;
import com.carto.geocoding.GeocodingRequest;
import com.carto.geocoding.GeocodingResult;
import com.carto.packagemanager.PackageManager;
import com.carto.projections.Projection;

/** @hidden */
@com.carto.utils.DontObfuscate public class PackageManagerGeocodingServiceModuleJNI {
  public final static native long new_PackageManagerGeocodingService(long jarg1, PackageManager jarg1_);
  public final static native void delete_PackageManagerGeocodingService(long jarg1);
  public final static native boolean PackageManagerGeocodingService_isAutocomplete(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native boolean PackageManagerGeocodingService_isAutocompleteSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native void PackageManagerGeocodingService_setAutocomplete(long jarg1, PackageManagerGeocodingService jarg1_, boolean jarg2);
  public final static native void PackageManagerGeocodingService_setAutocompleteSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_, boolean jarg2);
  public final static native String PackageManagerGeocodingService_getLanguage(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native String PackageManagerGeocodingService_getLanguageSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native void PackageManagerGeocodingService_setLanguage(long jarg1, PackageManagerGeocodingService jarg1_, String jarg2);
  public final static native void PackageManagerGeocodingService_setLanguageSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_, String jarg2);
  public final static native int PackageManagerGeocodingService_getMaxResults(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native int PackageManagerGeocodingService_getMaxResultsSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native void PackageManagerGeocodingService_setMaxResults(long jarg1, PackageManagerGeocodingService jarg1_, int jarg2);
  public final static native void PackageManagerGeocodingService_setMaxResultsSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_, int jarg2);
  public final static native long PackageManagerGeocodingService_calculateAddresses(long jarg1, PackageManagerGeocodingService jarg1_, long jarg2, GeocodingRequest jarg2_) throws java.io.IOException;
  public final static native long PackageManagerGeocodingService_calculateAddressesSwigExplicitPackageManagerGeocodingService(long jarg1, PackageManagerGeocodingService jarg1_, long jarg2, GeocodingRequest jarg2_) throws java.io.IOException;
  public final static native long PackageManagerGeocodingService_swigGetRawPtr(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native String PackageManagerGeocodingService_swigGetClassName(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native Object PackageManagerGeocodingService_swigGetDirectorObject(long jarg1, PackageManagerGeocodingService jarg1_);
  public final static native void PackageManagerGeocodingService_director_connect(PackageManagerGeocodingService obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void PackageManagerGeocodingService_change_ownership(PackageManagerGeocodingService obj, long cptr, boolean take_or_release);
  public final static native long PackageManagerGeocodingService_SWIGSmartPtrUpcast(long jarg1);

  public static boolean SwigDirector_PackageManagerGeocodingService_isAutocomplete(PackageManagerGeocodingService self) {
    return self.isAutocomplete();
  }
  public static void SwigDirector_PackageManagerGeocodingService_setAutocomplete(PackageManagerGeocodingService self, boolean autocomplete) {
    self.setAutocomplete(autocomplete);
  }
  public static String SwigDirector_PackageManagerGeocodingService_getLanguage(PackageManagerGeocodingService self) {
    return self.getLanguage();
  }
  public static void SwigDirector_PackageManagerGeocodingService_setLanguage(PackageManagerGeocodingService self, String lang) {
    self.setLanguage(lang);
  }
  public static int SwigDirector_PackageManagerGeocodingService_getMaxResults(PackageManagerGeocodingService self) {
    return self.getMaxResults();
  }
  public static void SwigDirector_PackageManagerGeocodingService_setMaxResults(PackageManagerGeocodingService self, int maxResults) {
    self.setMaxResults(maxResults);
  }
  public static long SwigDirector_PackageManagerGeocodingService_calculateAddresses(PackageManagerGeocodingService self, long request) throws java.io.IOException {
    return GeocodingResultVector.getCPtr(self.calculateAddresses(new GeocodingRequest(request, true)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
