/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geocoding;

import com.carto.geocoding.ReverseGeocodingService;
import com.carto.geocoding.ReverseGeocodingRequest;
import com.carto.geocoding.GeocodingResult;
import com.carto.packagemanager.PackageManager;
import com.carto.projections.Projection;

/**
 * A reverse geocoding service that uses geocoding packages from package manager.
 */
@com.carto.utils.DontObfuscate public class PackageManagerReverseGeocodingService extends ReverseGeocodingService {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public PackageManagerReverseGeocodingService(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(PackageManagerReverseGeocodingService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PackageManagerReverseGeocodingServiceModuleJNI.delete_PackageManagerReverseGeocodingService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.geocoding.PackageManagerReverseGeocodingService swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.geocoding.PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.geocoding.PackageManagerReverseGeocodingService) director;
    }

    String objClassName = com.carto.geocoding.PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_swigGetClassName(cPtr, null);
    com.carto.geocoding.PackageManagerReverseGeocodingService objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.geocoding." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.geocoding.PackageManagerReverseGeocodingService) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a new instance of the PackageManagerReverseGeocodingService given package manager instance.<br>
 * @param packageManager The package manager instance to use.
 */
  public PackageManagerReverseGeocodingService(PackageManager packageManager) {
    this(PackageManagerReverseGeocodingServiceModuleJNI.new_PackageManagerReverseGeocodingService(PackageManager.getCPtr(packageManager), packageManager), true);
    PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public String getLanguage() {
    return (getClass() == PackageManagerReverseGeocodingService.class) ? PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_getLanguage(swigCPtr, this) : PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_getLanguageSwigExplicitPackageManagerReverseGeocodingService(swigCPtr, this);
  }

  public void setLanguage(String lang) {
    if (getClass() == PackageManagerReverseGeocodingService.class) PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_setLanguage(swigCPtr, this, lang); else PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_setLanguageSwigExplicitPackageManagerReverseGeocodingService(swigCPtr, this, lang);
  }

  public GeocodingResultVector calculateAddresses(ReverseGeocodingRequest request) throws java.io.IOException {
    return new GeocodingResultVector((getClass() == PackageManagerReverseGeocodingService.class) ? PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_calculateAddresses(swigCPtr, this, ReverseGeocodingRequest.getCPtr(request), request) : PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_calculateAddressesSwigExplicitPackageManagerReverseGeocodingService(swigCPtr, this, ReverseGeocodingRequest.getCPtr(request), request), true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return PackageManagerReverseGeocodingServiceModuleJNI.PackageManagerReverseGeocodingService_swigGetDirectorObject(swigCPtr, this);
  }

}
