/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geocoding;

import com.carto.geocoding.GeocodingService;
import com.carto.geocoding.GeocodingRequest;
import com.carto.geocoding.GeocodingResult;
import com.carto.projections.Projection;

/** @hidden */
@com.carto.utils.DontObfuscate public class PeliasOnlineGeocodingServiceModuleJNI {
  public final static native long new_PeliasOnlineGeocodingService(String jarg1);
  public final static native void delete_PeliasOnlineGeocodingService(long jarg1);
  public final static native String PeliasOnlineGeocodingService_getCustomServiceURL(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native void PeliasOnlineGeocodingService_setCustomServiceURL(long jarg1, PeliasOnlineGeocodingService jarg1_, String jarg2);
  public final static native boolean PeliasOnlineGeocodingService_isAutocomplete(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native boolean PeliasOnlineGeocodingService_isAutocompleteSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native void PeliasOnlineGeocodingService_setAutocomplete(long jarg1, PeliasOnlineGeocodingService jarg1_, boolean jarg2);
  public final static native void PeliasOnlineGeocodingService_setAutocompleteSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_, boolean jarg2);
  public final static native String PeliasOnlineGeocodingService_getLanguage(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native String PeliasOnlineGeocodingService_getLanguageSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native void PeliasOnlineGeocodingService_setLanguage(long jarg1, PeliasOnlineGeocodingService jarg1_, String jarg2);
  public final static native void PeliasOnlineGeocodingService_setLanguageSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_, String jarg2);
  public final static native int PeliasOnlineGeocodingService_getMaxResults(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native int PeliasOnlineGeocodingService_getMaxResultsSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native void PeliasOnlineGeocodingService_setMaxResults(long jarg1, PeliasOnlineGeocodingService jarg1_, int jarg2);
  public final static native void PeliasOnlineGeocodingService_setMaxResultsSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_, int jarg2);
  public final static native long PeliasOnlineGeocodingService_calculateAddresses(long jarg1, PeliasOnlineGeocodingService jarg1_, long jarg2, GeocodingRequest jarg2_) throws java.io.IOException;
  public final static native long PeliasOnlineGeocodingService_calculateAddressesSwigExplicitPeliasOnlineGeocodingService(long jarg1, PeliasOnlineGeocodingService jarg1_, long jarg2, GeocodingRequest jarg2_) throws java.io.IOException;
  public final static native long PeliasOnlineGeocodingService_swigGetRawPtr(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native String PeliasOnlineGeocodingService_swigGetClassName(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native Object PeliasOnlineGeocodingService_swigGetDirectorObject(long jarg1, PeliasOnlineGeocodingService jarg1_);
  public final static native void PeliasOnlineGeocodingService_director_connect(PeliasOnlineGeocodingService obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void PeliasOnlineGeocodingService_change_ownership(PeliasOnlineGeocodingService obj, long cptr, boolean take_or_release);
  public final static native long PeliasOnlineGeocodingService_SWIGSmartPtrUpcast(long jarg1);

  public static boolean SwigDirector_PeliasOnlineGeocodingService_isAutocomplete(PeliasOnlineGeocodingService self) {
    return self.isAutocomplete();
  }
  public static void SwigDirector_PeliasOnlineGeocodingService_setAutocomplete(PeliasOnlineGeocodingService self, boolean autocomplete) {
    self.setAutocomplete(autocomplete);
  }
  public static String SwigDirector_PeliasOnlineGeocodingService_getLanguage(PeliasOnlineGeocodingService self) {
    return self.getLanguage();
  }
  public static void SwigDirector_PeliasOnlineGeocodingService_setLanguage(PeliasOnlineGeocodingService self, String lang) {
    self.setLanguage(lang);
  }
  public static int SwigDirector_PeliasOnlineGeocodingService_getMaxResults(PeliasOnlineGeocodingService self) {
    return self.getMaxResults();
  }
  public static void SwigDirector_PeliasOnlineGeocodingService_setMaxResults(PeliasOnlineGeocodingService self, int maxResults) {
    self.setMaxResults(maxResults);
  }
  public static long SwigDirector_PeliasOnlineGeocodingService_calculateAddresses(PeliasOnlineGeocodingService self, long request) throws java.io.IOException {
    return GeocodingResultVector.getCPtr(self.calculateAddresses(new GeocodingRequest(request, true)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
