/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.geocoding;

import com.carto.geocoding.GeocodingService;
import com.carto.geocoding.GeocodingRequest;
import com.carto.geocoding.GeocodingResult;
import com.carto.projections.Projection;

/**
 * An online geocoding service that uses TomTom geocoder.<br>
 * As the class connects to an external (non-CARTO) service, this class is provided "as-is",<br>
 * future changes from the service provider may not be compatible with the implementation.<br>
 * Geocoding and reverse geocoding perform network requests and must be executed in non-UI background thread.<br>
 * Be sure to read the Terms and Conditions of TomTom to see if the<br>
 * service is available for your application.<br>
 * Note: this class is experimental and may change or even be removed in future SDK versions.
 */
@com.carto.utils.DontObfuscate public class TomTomOnlineGeocodingService extends GeocodingService {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public TomTomOnlineGeocodingService(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(TomTomOnlineGeocodingService obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TomTomOnlineGeocodingServiceModuleJNI.delete_TomTomOnlineGeocodingService(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.geocoding.TomTomOnlineGeocodingService swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.geocoding.TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.geocoding.TomTomOnlineGeocodingService) director;
    }

    String objClassName = com.carto.geocoding.TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_swigGetClassName(cPtr, null);
    com.carto.geocoding.TomTomOnlineGeocodingService objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.geocoding." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.geocoding.TomTomOnlineGeocodingService) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a new instance of the TomTomOnlineGeocodingService given API key.<br>
 * @param apiKey The API key to use (registered with TomTom).
 */
  public TomTomOnlineGeocodingService(String apiKey) {
    this(TomTomOnlineGeocodingServiceModuleJNI.new_TomTomOnlineGeocodingService(apiKey), true);
    TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Returns the custom backend service URL.<br>
 * @return The custom backend service URL. If this is not defined, an empty string is returned.
 */
  public String getCustomServiceURL() {
    return TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_getCustomServiceURL(swigCPtr, this);
  }

/**
 * Sets the custom backend service URL. <br>
 * The custom URL may contain tag "{api_key}" which will be substituted with the set API key.<br>
 * The custom URL should contain tag "{mode}" which will be set either to "autocomplete" or "search" based on the autocomplete state.<br>
 * @param serviceURL The custom backend service URL to use. If this is empty, then the default service is used.
 */
  public void setCustomServiceURL(String serviceURL) {
    TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setCustomServiceURL(swigCPtr, this, serviceURL);
  }

  public boolean isAutocomplete() {
    return (getClass() == TomTomOnlineGeocodingService.class) ? TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_isAutocomplete(swigCPtr, this) : TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_isAutocompleteSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this);
  }

  public void setAutocomplete(boolean autocomplete) {
    if (getClass() == TomTomOnlineGeocodingService.class) TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setAutocomplete(swigCPtr, this, autocomplete); else TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setAutocompleteSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this, autocomplete);
  }

  public String getLanguage() {
    return (getClass() == TomTomOnlineGeocodingService.class) ? TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_getLanguage(swigCPtr, this) : TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_getLanguageSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this);
  }

  public void setLanguage(String lang) {
    if (getClass() == TomTomOnlineGeocodingService.class) TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setLanguage(swigCPtr, this, lang); else TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setLanguageSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this, lang);
  }

  public int getMaxResults() {
    return (getClass() == TomTomOnlineGeocodingService.class) ? TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_getMaxResults(swigCPtr, this) : TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_getMaxResultsSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this);
  }

  public void setMaxResults(int maxResults) {
    if (getClass() == TomTomOnlineGeocodingService.class) TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setMaxResults(swigCPtr, this, maxResults); else TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_setMaxResultsSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this, maxResults);
  }

  public GeocodingResultVector calculateAddresses(GeocodingRequest request) throws java.io.IOException {
    return new GeocodingResultVector((getClass() == TomTomOnlineGeocodingService.class) ? TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_calculateAddresses(swigCPtr, this, GeocodingRequest.getCPtr(request), request) : TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_calculateAddressesSwigExplicitTomTomOnlineGeocodingService(swigCPtr, this, GeocodingRequest.getCPtr(request), request), true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return TomTomOnlineGeocodingServiceModuleJNI.TomTomOnlineGeocodingService_swigGetDirectorObject(swigCPtr, this);
  }

}
