/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.renderers;

/**
 * An internal listener class for notifying about screen redraw requests.
 */
@com.carto.utils.DontObfuscate public class RedrawRequestListener {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public RedrawRequestListener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(RedrawRequestListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        RedrawRequestListenerModuleJNI.delete_RedrawRequestListener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    RedrawRequestListenerModuleJNI.RedrawRequestListener_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    RedrawRequestListenerModuleJNI.RedrawRequestListener_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.renderers.RedrawRequestListener swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.renderers.RedrawRequestListenerModuleJNI.RedrawRequestListener_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.renderers.RedrawRequestListener) director;
    }

    String objClassName = com.carto.renderers.RedrawRequestListenerModuleJNI.RedrawRequestListener_swigGetClassName(cPtr, null);
    com.carto.renderers.RedrawRequestListener objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.renderers." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.renderers.RedrawRequestListener) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Called when the screen needs to be redrawn.
 */
  public void onRedrawRequested() {
    if (getClass() == RedrawRequestListener.class) RedrawRequestListenerModuleJNI.RedrawRequestListener_onRedrawRequested(swigCPtr, this); else RedrawRequestListenerModuleJNI.RedrawRequestListener_onRedrawRequestedSwigExplicitRedrawRequestListener(swigCPtr, this);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return RedrawRequestListenerModuleJNI.RedrawRequestListener_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return RedrawRequestListenerModuleJNI.RedrawRequestListener_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return RedrawRequestListenerModuleJNI.RedrawRequestListener_swigGetDirectorObject(swigCPtr, this);
  }

  public RedrawRequestListener() {
    this(RedrawRequestListenerModuleJNI.new_RedrawRequestListener(), true);
    RedrawRequestListenerModuleJNI.RedrawRequestListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
