/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.Variant;
import com.carto.styles.BalloonPopupButtonStyle;

/**
 * A button that can be used to add interactivity to balloon popups.
 */
@com.carto.utils.DontObfuscate public class BalloonPopupButton {
  /** @hidden */
  private transient long swigCPtr;
  /** @hidden */
  protected transient boolean swigCMemOwn;

  /** @hidden */
  public BalloonPopupButton(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(BalloonPopupButton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        BalloonPopupButtonModuleJNI.delete_BalloonPopupButton(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.vectorelements.BalloonPopupButton swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.vectorelements.BalloonPopupButtonModuleJNI.BalloonPopupButton_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.vectorelements.BalloonPopupButton) director;
    }

    String objClassName = com.carto.vectorelements.BalloonPopupButtonModuleJNI.BalloonPopupButton_swigGetClassName(cPtr, null);
    com.carto.vectorelements.BalloonPopupButton objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.vectorelements." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.vectorelements.BalloonPopupButton) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a BalloonPopupButton object with the specified style and text.<br>
 * @param style The style that defines what this button looks like.<br>
 * @param text The text for this button.
 */
  public BalloonPopupButton(BalloonPopupButtonStyle style, String text) {
    this(BalloonPopupButtonModuleJNI.new_BalloonPopupButton(BalloonPopupButtonStyle.getCPtr(style), style, text), true);
  }

/**
 * Returns the text of this button.<br>
 * @return The text of this button.
 */
  public String getText() {
    return BalloonPopupButtonModuleJNI.BalloonPopupButton_getText(swigCPtr, this);
  }

/**
 * Returns the style of this button.<br>
 * @return The style that defines what this button looks like.
 */
  public BalloonPopupButtonStyle getStyle() {
  long cPtr = BalloonPopupButtonModuleJNI.BalloonPopupButton_getStyle(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.styles.BalloonPopupButtonStyle.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Returns the user-defined tag associated with the button.<br>
 * @return The user-defined tag value. By default the tag is empty.
 */
  public Variant getTag() { return new Variant(BalloonPopupButtonModuleJNI.BalloonPopupButton_getTag(swigCPtr, this), true); }

/**
 * Sets the user-defined tag associated with the button.<br>
 * @param tag The new user-defined tag value.
 */
  public void setTag(Variant tag) {
    BalloonPopupButtonModuleJNI.BalloonPopupButton_setTag(swigCPtr, this, Variant.getCPtr(tag), tag);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return BalloonPopupButtonModuleJNI.BalloonPopupButton_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return BalloonPopupButtonModuleJNI.BalloonPopupButton_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return BalloonPopupButtonModuleJNI.BalloonPopupButton_swigGetDirectorObject(swigCPtr, this);
  }

}
