/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.MapBounds;
import com.carto.core.MapPos;
import com.carto.geometry.Geometry;
import com.carto.styles.BillboardStyle;
import com.carto.vectorelements.VectorElement;

/** @hidden */
@com.carto.utils.DontObfuscate public class BillboardModuleJNI {
  public final static native void delete_Billboard(long jarg1);
  public final static native long Billboard_getBaseBillboard(long jarg1, Billboard jarg1_);
  public final static native void Billboard_setBaseBillboard(long jarg1, Billboard jarg1_, long jarg2, Billboard jarg2_);
  public final static native long Billboard_getBounds(long jarg1, Billboard jarg1_);
  public final static native long Billboard_getRootGeometry(long jarg1, Billboard jarg1_);
  public final static native long Billboard_getGeometry(long jarg1, Billboard jarg1_);
  public final static native void Billboard_setGeometry(long jarg1, Billboard jarg1_, long jarg2, Geometry jarg2_);
  public final static native void Billboard_setPos(long jarg1, Billboard jarg1_, long jarg2, MapPos jarg2_);
  public final static native float Billboard_getRotation(long jarg1, Billboard jarg1_);
  public final static native void Billboard_setRotation(long jarg1, Billboard jarg1_, float jarg2);
  public final static native long Billboard_swigGetRawPtr(long jarg1, Billboard jarg1_);
  public final static native String Billboard_swigGetClassName(long jarg1, Billboard jarg1_);
  public final static native Object Billboard_swigGetDirectorObject(long jarg1, Billboard jarg1_);
  public final static native long Billboard_SWIGSmartPtrUpcast(long jarg1);
}
