/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.MapPos;
import com.carto.graphics.Bitmap;
import com.carto.geometry.Geometry;
import com.carto.styles.MarkerStyle;
import com.carto.vectorelements.Billboard;

/**
 * A billboard element with a static bitmap that can be displayed on the map.
 */
@com.carto.utils.DontObfuscate public class Marker extends Billboard {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public Marker(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(Marker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MarkerModuleJNI.delete_Marker(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.vectorelements.Marker swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.vectorelements.MarkerModuleJNI.Marker_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.vectorelements.Marker) director;
    }

    String objClassName = com.carto.vectorelements.MarkerModuleJNI.Marker_swigGetClassName(cPtr, null);
    com.carto.vectorelements.Marker objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.vectorelements." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.vectorelements.Marker) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a Marker object with the specified style and attaches it to a billboard element.<br>
 * @param baseBillboard The billboard this billboard will be attached to.<br>
 * @param style The style that defines what this marker looks like.
 */
  public Marker(Billboard baseBillboard, MarkerStyle style) {
    this(MarkerModuleJNI.new_Marker__SWIG_0(Billboard.getCPtr(baseBillboard), baseBillboard, MarkerStyle.getCPtr(style), style), true);
  }

/**
 * Constructs a Marker object from a geometry object and a style.<br>
 * @param geometry The geometry object that defines the location of this marker.<br>
 * @param style The style that defines what this marker looks like.
 */
  public Marker(Geometry geometry, MarkerStyle style) {
    this(MarkerModuleJNI.new_Marker__SWIG_1(Geometry.getCPtr(geometry), geometry, MarkerStyle.getCPtr(style), style), true);
  }

/**
 * Constructs a Marker object from a map position and a style.<br>
 * @param pos The map position that defines the location of this marker.<br>
 * @param style The style that defines what this marker looks like.
 */
  public Marker(MapPos pos, MarkerStyle style) {
    this(MarkerModuleJNI.new_Marker__SWIG_2(MapPos.getCPtr(pos), pos, MarkerStyle.getCPtr(style), style), true);
  }

/**
 * Returns the style of this marker.<br>
 * @return The style that defines what this marker looks like.
 */
  public MarkerStyle getStyle() {
  long cPtr = MarkerModuleJNI.Marker_getStyle(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.styles.MarkerStyle.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Sets the style for this marker.<br>
 * @param style The new style that defines what this marker looks like.
 */
  public void setStyle(MarkerStyle style) {
    MarkerModuleJNI.Marker_setStyle(swigCPtr, this, MarkerStyle.getCPtr(style), style);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return MarkerModuleJNI.Marker_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return MarkerModuleJNI.Marker_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return MarkerModuleJNI.Marker_swigGetDirectorObject(swigCPtr, this);
  }

}
