/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.BinaryData;
import com.carto.core.MapBounds;
import com.carto.core.MapPos;
import com.carto.core.MapVec;
import com.carto.geometry.Geometry;
import com.carto.styles.NMLModelStyle;
import com.carto.vectorelements.Billboard;

/** @hidden */
@com.carto.utils.DontObfuscate public class NMLModelModuleJNI {
  public final static native long new_NMLModel__SWIG_0(long jarg1, Billboard jarg1_, long jarg2, NMLModelStyle jarg2_);
  public final static native long new_NMLModel__SWIG_1(long jarg1, Geometry jarg1_, long jarg2, NMLModelStyle jarg2_);
  public final static native long new_NMLModel__SWIG_2(long jarg1, MapPos jarg1_, long jarg2, NMLModelStyle jarg2_);
  public final static native void delete_NMLModel(long jarg1);
  public final static native float NMLModel_getRotationAngle(long jarg1, NMLModel jarg1_);
  public final static native void NMLModel_setRotationAngle(long jarg1, NMLModel jarg1_, float jarg2);
  public final static native long NMLModel_getRotationAxis(long jarg1, NMLModel jarg1_);
  public final static native void NMLModel_setRotationAxis(long jarg1, NMLModel jarg1_, long jarg2, MapVec jarg2_);
  public final static native void NMLModel_setRotation(long jarg1, NMLModel jarg1_, long jarg2, MapVec jarg2_, float jarg3);
  public final static native float NMLModel_getScale(long jarg1, NMLModel jarg1_);
  public final static native void NMLModel_setScale(long jarg1, NMLModel jarg1_, float jarg2);
  public final static native long NMLModel_getStyle(long jarg1, NMLModel jarg1_);
  public final static native void NMLModel_setStyle(long jarg1, NMLModel jarg1_, long jarg2, NMLModelStyle jarg2_);
  public final static native long NMLModel_swigGetRawPtr(long jarg1, NMLModel jarg1_);
  public final static native String NMLModel_swigGetClassName(long jarg1, NMLModel jarg1_);
  public final static native Object NMLModel_swigGetDirectorObject(long jarg1, NMLModel jarg1_);
  public final static native long NMLModel_SWIGSmartPtrUpcast(long jarg1);
}
