/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.MapPos;
import com.carto.geometry.PointGeometry;
import com.carto.styles.PointStyle;
import com.carto.vectorelements.VectorElement;

/** @hidden */
@com.carto.utils.DontObfuscate public class PointModuleJNI {
  public final static native long new_Point__SWIG_0(long jarg1, PointGeometry jarg1_, long jarg2, PointStyle jarg2_);
  public final static native long new_Point__SWIG_1(long jarg1, MapPos jarg1_, long jarg2, PointStyle jarg2_);
  public final static native void delete_Point(long jarg1);
  public final static native long Point_getGeometry(long jarg1, Point jarg1_);
  public final static native void Point_setGeometry(long jarg1, Point jarg1_, long jarg2, PointGeometry jarg2_);
  public final static native long Point_getPos(long jarg1, Point jarg1_);
  public final static native void Point_setPos(long jarg1, Point jarg1_, long jarg2, MapPos jarg2_);
  public final static native long Point_getStyle(long jarg1, Point jarg1_);
  public final static native void Point_setStyle(long jarg1, Point jarg1_, long jarg2, PointStyle jarg2_);
  public final static native long Point_swigGetRawPtr(long jarg1, Point jarg1_);
  public final static native String Point_swigGetClassName(long jarg1, Point jarg1_);
  public final static native Object Point_swigGetDirectorObject(long jarg1, Point jarg1_);
  public final static native long Point_SWIGSmartPtrUpcast(long jarg1);
}
