/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.MapPos;
import com.carto.geometry.PointGeometry;
import com.carto.styles.PointStyle;
import com.carto.vectorelements.VectorElement;

/**
 * A geometric point that can be displayed on the map.
 */
@com.carto.utils.DontObfuscate public class Point extends VectorElement {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public Point(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(Point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PointModuleJNI.delete_Point(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.vectorelements.Point swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.vectorelements.PointModuleJNI.Point_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.vectorelements.Point) director;
    }

    String objClassName = com.carto.vectorelements.PointModuleJNI.Point_swigGetClassName(cPtr, null);
    com.carto.vectorelements.Point objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.vectorelements." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.vectorelements.Point) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a Point object from a geometry object and a style.<br>
 * @param geometry The geometry object that defines the location of this point.<br>
 * @param style The style that defines what this point looks like.
 */
  public Point(PointGeometry geometry, PointStyle style) {
    this(PointModuleJNI.new_Point__SWIG_0(PointGeometry.getCPtr(geometry), geometry, PointStyle.getCPtr(style), style), true);
  }

/**
 * Constructs a Point object from a map position and a style.<br>
 * @param pos The map position that defines the location of this point.<br>
 * @param style The style that defines what this point looks like.
 */
  public Point(MapPos pos, PointStyle style) {
    this(PointModuleJNI.new_Point__SWIG_1(MapPos.getCPtr(pos), pos, PointStyle.getCPtr(style), style), true);
  }

  public PointGeometry getGeometry() {
  long cPtr = PointModuleJNI.Point_getGeometry(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.PointGeometry.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Sets the location for this point.<br>
 * @param geometry The new geometry object that defines the location of this point.
 */
  public void setGeometry(PointGeometry geometry) {
    PointModuleJNI.Point_setGeometry(swigCPtr, this, PointGeometry.getCPtr(geometry), geometry);
  }

/**
 * Returns the location of this point.<br>
 * @return The map position that defines the location of this point.
 */
  public MapPos getPos() { return new MapPos(PointModuleJNI.Point_getPos(swigCPtr, this), true); }

/**
 * Sets the location of this point.<br>
 * @param pos The new map position that defines the location of this point.
 */
  public void setPos(MapPos pos) {
    PointModuleJNI.Point_setPos(swigCPtr, this, MapPos.getCPtr(pos), pos);
  }

/**
 * Returns the style of this point.<br>
 * @return The style that defines what this point looks like.
 */
  public PointStyle getStyle() {
  long cPtr = PointModuleJNI.Point_getStyle(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.styles.PointStyle.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Sets a style for this point.<br>
 * @param style The new style that defines what this point looks like.
 */
  public void setStyle(PointStyle style) {
    PointModuleJNI.Point_setStyle(swigCPtr, this, PointStyle.getCPtr(style), style);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return PointModuleJNI.Point_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return PointModuleJNI.Point_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return PointModuleJNI.Point_swigGetDirectorObject(swigCPtr, this);
  }

}
