/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.MapPosVector;
import com.carto.core.MapPosVectorVector;
import com.carto.geometry.PolygonGeometry;
import com.carto.styles.Polygon3DStyle;
import com.carto.vectorelements.VectorElement;

/**
 * A geometric 3d polygon that can be displayed on the map.<br>
 * 3d polygons can be concave and have multiple overlapping holes.
 */
@com.carto.utils.DontObfuscate public class Polygon3D extends VectorElement {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public Polygon3D(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(Polygon3D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        Polygon3DModuleJNI.delete_Polygon3D(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.vectorelements.Polygon3D swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.vectorelements.Polygon3DModuleJNI.Polygon3D_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.vectorelements.Polygon3D) director;
    }

    String objClassName = com.carto.vectorelements.Polygon3DModuleJNI.Polygon3D_swigGetClassName(cPtr, null);
    com.carto.vectorelements.Polygon3D objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.vectorelements." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.vectorelements.Polygon3D) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a Polygon3D object from a geometry object and a style.<br>
 * @param geometry The geometry object that defines the location and holes of this 3d polygon.<br>
 * @param style The style that defines what this 3d polygon looks like.<br>
 * @param height The height of this 3d polygon in meters.
 */
  public Polygon3D(PolygonGeometry geometry, Polygon3DStyle style, float height) {
    this(Polygon3DModuleJNI.new_Polygon3D__SWIG_0(PolygonGeometry.getCPtr(geometry), geometry, Polygon3DStyle.getCPtr(style), style, height), true);
  }

/**
 * Constructs a Polygon3D object from a vector of map positions and a style.<br>
 * @param poses The vector of map positions that defines the location of this 3d polygon.<br>
 * @param style The style that defines what this 3d polygon looks like.<br>
 * @param height The height of this 3d polygon in meters.
 */
  public Polygon3D(MapPosVector poses, Polygon3DStyle style, float height) {
    this(Polygon3DModuleJNI.new_Polygon3D__SWIG_1(MapPosVector.getCPtr(poses), poses, Polygon3DStyle.getCPtr(style), style, height), true);
  }

/**
 * Constructs a Polygon3D object from a vector of map positions, a vector of holes and a style.<br>
 * @param poses The vector of map positions that defines the location of this 3d polygon.<br>
 * @param holes The vector of holes that defines the locations of holes of this 3d polygon.<br>
 * @param style The style that defines what this 3d polygon looks like.<br>
 * @param height The height of this 3d polygon in meters.
 */
  public Polygon3D(MapPosVector poses, MapPosVectorVector holes, Polygon3DStyle style, float height) {
    this(Polygon3DModuleJNI.new_Polygon3D__SWIG_2(MapPosVector.getCPtr(poses), poses, MapPosVectorVector.getCPtr(holes), holes, Polygon3DStyle.getCPtr(style), style, height), true);
  }

  public PolygonGeometry getGeometry() {
  long cPtr = Polygon3DModuleJNI.Polygon3D_getGeometry(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.geometry.PolygonGeometry.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Sets the location for this 3d polygon.<br>
 * @param geometry The new geometry object that defines the location and holes of this 3d polygon.
 */
  public void setGeometry(PolygonGeometry geometry) {
    Polygon3DModuleJNI.Polygon3D_setGeometry(swigCPtr, this, PolygonGeometry.getCPtr(geometry), geometry);
  }

/**
 * Returns the vertices that define this 3d polygon.<br>
 * @return The new vector of map positions that define this 3d polygon.
 */
  public MapPosVector getPoses() { return new MapPosVector(Polygon3DModuleJNI.Polygon3D_getPoses(swigCPtr, this), true); }

/**
 * Sets the vertices that define this 3d polygon.<br>
 * Note: holes are not affected by this call.<br>
 * @param poses The new vector of map positions that define this 3d polygon.
 */
  public void setPoses(MapPosVector poses) {
    Polygon3DModuleJNI.Polygon3D_setPoses(swigCPtr, this, MapPosVector.getCPtr(poses), poses);
  }

/**
 * Returns the holes of the 3d polygon.<br>
 * @return The list of holes of the 3d polygon.
 */
  public MapPosVectorVector getHoles() { return new MapPosVectorVector(Polygon3DModuleJNI.Polygon3D_getHoles(swigCPtr, this), true); }

/**
 * Sets the holes of the 3d polygon.<br>
 * @param holes The list of holes of the 3d polygon.
 */
  public void setHoles(MapPosVectorVector holes) {
    Polygon3DModuleJNI.Polygon3D_setHoles(swigCPtr, this, MapPosVectorVector.getCPtr(holes), holes);
  }

/**
 * Returns the height of this 3d polygon.<br>
 * @return The height of this 3d polygon in meters.
 */
  public float getHeight() {
    return Polygon3DModuleJNI.Polygon3D_getHeight(swigCPtr, this);
  }

/**
 * Sets the height for this 3d polygon.<br>
 * @param height The new height for this 3d polygon in meters.
 */
  public void setHeight(float height) {
    Polygon3DModuleJNI.Polygon3D_setHeight(swigCPtr, this, height);
  }

/**
 * Returns the style of this 3d polygon.<br>
 * @return The style that defines what this 3d polygon looks like.
 */
  public Polygon3DStyle getStyle() {
  long cPtr = Polygon3DModuleJNI.Polygon3D_getStyle(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.styles.Polygon3DStyle.swigCreatePolymorphicInstance(cPtr, true);
}

/**
 * Sets the style for this 3d polygon.<br>
 * @param style The new style that defines what this 3d polygon looks like.
 */
  public void setStyle(Polygon3DStyle style) {
    Polygon3DModuleJNI.Polygon3D_setStyle(swigCPtr, this, Polygon3DStyle.getCPtr(style), style);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return Polygon3DModuleJNI.Polygon3D_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return Polygon3DModuleJNI.Polygon3D_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return Polygon3DModuleJNI.Polygon3D_swigGetDirectorObject(swigCPtr, this);
  }

}
