/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectorelements;

import com.carto.core.MapPos;
import com.carto.graphics.Bitmap;
import com.carto.geometry.Geometry;
import com.carto.styles.TextStyle;
import com.carto.vectorelements.Label;

/** @hidden */
@com.carto.utils.DontObfuscate public class TextModuleJNI {
  public final static native long new_Text__SWIG_0(long jarg1, Billboard jarg1_, long jarg2, TextStyle jarg2_, String jarg3);
  public final static native long new_Text__SWIG_1(long jarg1, Geometry jarg1_, long jarg2, TextStyle jarg2_, String jarg3);
  public final static native long new_Text__SWIG_2(long jarg1, MapPos jarg1_, long jarg2, TextStyle jarg2_, String jarg3);
  public final static native void delete_Text(long jarg1);
  public final static native long Text_drawBitmap(long jarg1, Text jarg1_, float jarg2);
  public final static native String Text_getText(long jarg1, Text jarg1_);
  public final static native void Text_setText(long jarg1, Text jarg1_, String jarg2);
  public final static native long Text_getStyle(long jarg1, Text jarg1_);
  public final static native void Text_setStyle(long jarg1, Text jarg1_, long jarg2, TextStyle jarg2_);
  public final static native long Text_swigGetRawPtr(long jarg1, Text jarg1_);
  public final static native String Text_swigGetClassName(long jarg1, Text jarg1_);
  public final static native Object Text_swigGetDirectorObject(long jarg1, Text jarg1_);
  public final static native long Text_SWIGSmartPtrUpcast(long jarg1);
}
