/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.datasources;

import com.carto.core.MapBounds;
import com.carto.datasources.VectorDataSource;
import com.carto.datasources.components.VectorData;
import com.carto.geometry.FeatureCollection;
import com.carto.geometry.GeometrySimplifier;
import com.carto.projections.Projection;
import com.carto.renderers.components.CullState;
import com.carto.styles.Style;
import com.carto.vectorelements.VectorElement;
import com.carto.vectorelements.VectorElementVector;

/** @hidden */
@com.carto.utils.DontObfuscate public class LocalVectorDataSourceModuleJNI {
  public final static native long new_LocalVectorDataSource__SWIG_0(long jarg1, Projection jarg1_);
  public final static native long new_LocalVectorDataSource__SWIG_1(long jarg1, Projection jarg1_, int jarg2);
  public final static native void delete_LocalVectorDataSource(long jarg1);
  public final static native void LocalVectorDataSource_clear(long jarg1, LocalVectorDataSource jarg1_);
  public final static native long LocalVectorDataSource_getAll(long jarg1, LocalVectorDataSource jarg1_);
  public final static native void LocalVectorDataSource_setAll(long jarg1, LocalVectorDataSource jarg1_, long jarg2, VectorElementVector jarg2_);
  public final static native void LocalVectorDataSource_add(long jarg1, LocalVectorDataSource jarg1_, long jarg2, VectorElement jarg2_);
  public final static native void LocalVectorDataSource_addAll(long jarg1, LocalVectorDataSource jarg1_, long jarg2, VectorElementVector jarg2_);
  public final static native boolean LocalVectorDataSource_remove(long jarg1, LocalVectorDataSource jarg1_, long jarg2, VectorElement jarg2_);
  public final static native boolean LocalVectorDataSource_removeAll(long jarg1, LocalVectorDataSource jarg1_, long jarg2, VectorElementVector jarg2_);
  public final static native long LocalVectorDataSource_getGeometrySimplifier(long jarg1, LocalVectorDataSource jarg1_);
  public final static native void LocalVectorDataSource_setGeometrySimplifier(long jarg1, LocalVectorDataSource jarg1_, long jarg2, GeometrySimplifier jarg2_);
  public final static native long LocalVectorDataSource_getFeatureCollection(long jarg1, LocalVectorDataSource jarg1_);
  public final static native void LocalVectorDataSource_addFeatureCollection(long jarg1, LocalVectorDataSource jarg1_, long jarg2, FeatureCollection jarg2_, long jarg3, Style jarg3_);
  public final static native long LocalVectorDataSource_getDataExtent(long jarg1, LocalVectorDataSource jarg1_);
  public final static native long LocalVectorDataSource_getDataExtentSwigExplicitLocalVectorDataSource(long jarg1, LocalVectorDataSource jarg1_);
  public final static native long LocalVectorDataSource_loadElements(long jarg1, LocalVectorDataSource jarg1_, long jarg2, CullState jarg2_);
  public final static native long LocalVectorDataSource_loadElementsSwigExplicitLocalVectorDataSource(long jarg1, LocalVectorDataSource jarg1_, long jarg2, CullState jarg2_);
  public final static native long LocalVectorDataSource_swigGetRawPtr(long jarg1, LocalVectorDataSource jarg1_);
  public final static native String LocalVectorDataSource_swigGetClassName(long jarg1, LocalVectorDataSource jarg1_);
  public final static native Object LocalVectorDataSource_swigGetDirectorObject(long jarg1, LocalVectorDataSource jarg1_);
  public final static native void LocalVectorDataSource_director_connect(LocalVectorDataSource obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void LocalVectorDataSource_change_ownership(LocalVectorDataSource obj, long cptr, boolean take_or_release);
  public final static native long LocalVectorDataSource_SWIGSmartPtrUpcast(long jarg1);

  public static long SwigDirector_LocalVectorDataSource_getDataExtent(LocalVectorDataSource self) {
    return MapBounds.getCPtr(self.getDataExtent());
  }
  public static long SwigDirector_LocalVectorDataSource_loadElements(LocalVectorDataSource self, long cullState) {
    return VectorData.getCPtr(self.loadElements(new CullState(cullState, true)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
