/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.datasources;

import com.carto.core.MapTile;
import com.carto.core.MapBounds;
import com.carto.core.StringMap;
import com.carto.datasources.TileDataSource;
import com.carto.datasources.components.TileData;

/** @hidden */
@com.carto.utils.DontObfuscate public class MapTilerOnlineTileDataSourceModuleJNI {
  public final static native long new_MapTilerOnlineTileDataSource(String jarg1);
  public final static native void delete_MapTilerOnlineTileDataSource(long jarg1);
  public final static native String MapTilerOnlineTileDataSource_getCustomServiceURL(long jarg1, MapTilerOnlineTileDataSource jarg1_);
  public final static native void MapTilerOnlineTileDataSource_setCustomServiceURL(long jarg1, MapTilerOnlineTileDataSource jarg1_, String jarg2);
  public final static native int MapTilerOnlineTileDataSource_getTimeout(long jarg1, MapTilerOnlineTileDataSource jarg1_);
  public final static native void MapTilerOnlineTileDataSource_setTimeout(long jarg1, MapTilerOnlineTileDataSource jarg1_, int jarg2);
  public final static native long MapTilerOnlineTileDataSource_loadTile(long jarg1, MapTilerOnlineTileDataSource jarg1_, long jarg2, MapTile jarg2_);
  public final static native long MapTilerOnlineTileDataSource_loadTileSwigExplicitMapTilerOnlineTileDataSource(long jarg1, MapTilerOnlineTileDataSource jarg1_, long jarg2, MapTile jarg2_);
  public final static native long MapTilerOnlineTileDataSource_swigGetRawPtr(long jarg1, MapTilerOnlineTileDataSource jarg1_);
  public final static native String MapTilerOnlineTileDataSource_swigGetClassName(long jarg1, MapTilerOnlineTileDataSource jarg1_);
  public final static native Object MapTilerOnlineTileDataSource_swigGetDirectorObject(long jarg1, MapTilerOnlineTileDataSource jarg1_);
  public final static native void MapTilerOnlineTileDataSource_director_connect(MapTilerOnlineTileDataSource obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MapTilerOnlineTileDataSource_change_ownership(MapTilerOnlineTileDataSource obj, long cptr, boolean take_or_release);
  public final static native long MapTilerOnlineTileDataSource_SWIGSmartPtrUpcast(long jarg1);

  public static int SwigDirector_MapTilerOnlineTileDataSource_getMinZoom(MapTilerOnlineTileDataSource self) {
    return self.getMinZoom();
  }
  public static int SwigDirector_MapTilerOnlineTileDataSource_getMaxZoom(MapTilerOnlineTileDataSource self) {
    return self.getMaxZoom();
  }
  public static long SwigDirector_MapTilerOnlineTileDataSource_getDataExtent(MapTilerOnlineTileDataSource self) {
    return MapBounds.getCPtr(self.getDataExtent());
  }
  public static long SwigDirector_MapTilerOnlineTileDataSource_loadTile(MapTilerOnlineTileDataSource self, long mapTile) {
    return TileData.getCPtr(self.loadTile(new MapTile(mapTile, true)));
  }
  public static void SwigDirector_MapTilerOnlineTileDataSource_notifyTilesChanged(MapTilerOnlineTileDataSource self, boolean removeTiles) {
    self.notifyTilesChanged(removeTiles);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
