/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.datasources;

import com.carto.core.MapTile;
import com.carto.core.MapBounds;
import com.carto.core.StringMap;
import com.carto.datasources.TileDataSource;
import com.carto.datasources.components.TileData;
import com.carto.packagemanager.PackageManager;

/**
 * A tile data source that loads tiles from package manager.
 */
@com.carto.utils.DontObfuscate public class PackageManagerTileDataSource extends TileDataSource {
  /** @hidden */
  private transient long swigCPtr;

  /** @hidden */
  public PackageManagerTileDataSource(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
    swigCPtr = cPtr;
  }

  /** @hidden */
  public static long getCPtr(PackageManagerTileDataSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /** @hidden */
  protected void finalize() {
    delete();
  }

  /** @hidden */
  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PackageManagerTileDataSourceModuleJNI.delete_PackageManagerTileDataSource(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  /** @hidden */
  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  /** @hidden */
  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_change_ownership(this, swigCPtr, false);
  }

  /** @hidden */
  public void swigTakeOwnership() {
    swigCMemOwn = true;
    PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_change_ownership(this, swigCPtr, true);
  }


  /**
   * Creates a polymorphic instance of the given native object. This is used internally by the SDK.
   * @param cPtr The native pointer of the instance.
   * @param cMemoryOwn The ownership flag.
   * @return The created instance.
   */
  /** @hidden */
  public static com.carto.datasources.PackageManagerTileDataSource swigCreatePolymorphicInstance(long cPtr, boolean cMemoryOwn) {
    if (cPtr == 0) {
      return null;
    }

    Object director = com.carto.datasources.PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_swigGetDirectorObject(cPtr, null);
    if (director != null) {
      return (com.carto.datasources.PackageManagerTileDataSource) director;
    }

    String objClassName = com.carto.datasources.PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_swigGetClassName(cPtr, null);
    com.carto.datasources.PackageManagerTileDataSource objInstance = null;
    try {
      Class<?> objClass = Class.forName("com.carto.datasources." + objClassName);
      Class<?>[] argTypes = new Class<?>[] {long.class, boolean.class};
      Object[] args = new Object[] {cPtr, cMemoryOwn};
      java.lang.reflect.Constructor<?> constructor = objClass.getDeclaredConstructor(argTypes);
      objInstance = (com.carto.datasources.PackageManagerTileDataSource) constructor.newInstance(args);
    } catch (Exception e) {
      com.carto.utils.Log.error("Carto Mobile SDK: Could not instantiate class: " + objClassName + " error: " + e.getMessage());
    }
    return objInstance;
  }


/**
 * Constructs a PackageManagerTileDataSource object.<br>
 * @param packageManager The package manager that is used to retrieve requested tiles.
 */
  public PackageManagerTileDataSource(PackageManager packageManager) {
    this(PackageManagerTileDataSourceModuleJNI.new_PackageManagerTileDataSource(PackageManager.getCPtr(packageManager), packageManager), true);
    PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

/**
 * Returns the package manager instance used by the data source.<br>
 * @return The package manager instance used by the data source.
 */
  public PackageManager getPackageManager() {
  long cPtr = PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_getPackageManager(swigCPtr, this);
  if (cPtr == 0) {
    return null;
  }
  /** @hidden */
  return com.carto.packagemanager.PackageManager.swigCreatePolymorphicInstance(cPtr, true);
}

  public TileData loadTile(MapTile mapTile) {
    long cPtr = (getClass() == PackageManagerTileDataSource.class) ? PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_loadTile(swigCPtr, this, MapTile.getCPtr(mapTile), mapTile) : PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_loadTileSwigExplicitPackageManagerTileDataSource(swigCPtr, this, MapTile.getCPtr(mapTile), mapTile);
    return (cPtr == 0) ? null : new TileData(cPtr, true);
  }

/**
 * Returns the raw pointer to the object. This is used internally by the SDK.<br>
 * @return The internal pointer of the object.
 */
  /** @hidden */
  public long swigGetRawPtr() {
    return PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_swigGetRawPtr(swigCPtr, this);
  }

/**
 * Returns the actual class name of this object. This is used internally by the SDK.<br>
 * @return The class name of this object.
 */
  /** @hidden */
  public String swigGetClassName() {
    return PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_swigGetClassName(swigCPtr, this);
  }

/**
 * Returns the connected director object. This is used internally by the SDK.<br>
 * @return The connected director object or null if director is not connected.
 */
  /** @hidden */
  public Object swigGetDirectorObject() {
    return PackageManagerTileDataSourceModuleJNI.PackageManagerTileDataSource_swigGetDirectorObject(swigCPtr, this);
  }

}
