/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.datasources;

import com.carto.core.MapBounds;
import com.carto.datasources.components.VectorData;
import com.carto.projections.Projection;
import com.carto.renderers.components.CullState;
import com.carto.graphics.ViewState;

/** @hidden */
@com.carto.utils.DontObfuscate public class VectorDataSourceModuleJNI {
  public final static native void delete_VectorDataSource(long jarg1);
  public final static native long VectorDataSource_getDataExtent(long jarg1, VectorDataSource jarg1_);
  public final static native long VectorDataSource_getDataExtentSwigExplicitVectorDataSource(long jarg1, VectorDataSource jarg1_);
  public final static native long VectorDataSource_getProjection(long jarg1, VectorDataSource jarg1_);
  public final static native long VectorDataSource_loadElements(long jarg1, VectorDataSource jarg1_, long jarg2, CullState jarg2_);
  public final static native void VectorDataSource_notifyElementsChanged(long jarg1, VectorDataSource jarg1_);
  public final static native long new_VectorDataSource(long jarg1, Projection jarg1_);
  public final static native long VectorDataSource_swigGetRawPtr(long jarg1, VectorDataSource jarg1_);
  public final static native String VectorDataSource_swigGetClassName(long jarg1, VectorDataSource jarg1_);
  public final static native Object VectorDataSource_swigGetDirectorObject(long jarg1, VectorDataSource jarg1_);
  public final static native void VectorDataSource_director_connect(VectorDataSource obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void VectorDataSource_change_ownership(VectorDataSource obj, long cptr, boolean take_or_release);

  public static long SwigDirector_VectorDataSource_getDataExtent(VectorDataSource self) {
    return MapBounds.getCPtr(self.getDataExtent());
  }
  public static long SwigDirector_VectorDataSource_loadElements(VectorDataSource self, long cullState) {
    return VectorData.getCPtr(self.loadElements(new CullState(cullState, true)));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
