/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.carto.vectortiles;

import com.carto.core.BinaryData;
import com.carto.graphics.Color;

/** @hidden */
@com.carto.utils.DontObfuscate public class VectorTileDecoderModuleJNI {
  public final static native void delete_VectorTileDecoder(long jarg1);
  public final static native void VectorTileDecoder_addFallbackFont(long jarg1, VectorTileDecoder jarg1_, long jarg2, BinaryData jarg2_);
  public final static native int VectorTileDecoder_getMinZoom(long jarg1, VectorTileDecoder jarg1_);
  public final static native int VectorTileDecoder_getMaxZoom(long jarg1, VectorTileDecoder jarg1_);
  public final static native void VectorTileDecoder_notifyDecoderChanged(long jarg1, VectorTileDecoder jarg1_);
  public final static native long VectorTileDecoder_swigGetRawPtr(long jarg1, VectorTileDecoder jarg1_);
  public final static native String VectorTileDecoder_swigGetClassName(long jarg1, VectorTileDecoder jarg1_);
  public final static native Object VectorTileDecoder_swigGetDirectorObject(long jarg1, VectorTileDecoder jarg1_);
}
